// nl-filter-patch — turn a bettor's sentence into a validated filter PATCH for the NFL Historical
// Analysis page. The model only *proposes* ops; the client re-validates every op with the shared
// applyFilterPatch reducer before applying, so a bad model output cannot produce a wrong query.
//
// The system prompt + output schema are GENERATED from src/features/analysis/filterSchema.ts into
// ./schema.json (a parity test fails the build on drift) — this function never hand-maintains a copy.
//
// Request  { sentence: string, currentFilter?: object, coaches?: string[], referees?: string[] }
// Response { ops: PatchOp[], couldnt_map: string[], ambiguous: string[] }
import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
// Import (not file-read) so the deploy bundler includes schema.json in the function bundle.
import artifactNfl from './schema.json' with { type: 'json' };
import artifactCfb from './schema.cfb.json' with { type: 'json' };
import artifactMlb from './schema.mlb.json' with { type: 'json' };
// Bundled copy of the shared validator (regenerated by scripts/gen-nl-filter-schema.ts) — the SAME
// engine the web runs client-side, so server-validated results can never drift from web behavior.
import {
  applySportFilterPatch,
  normalizeNflSavedFilterSnapshot, normalizeCfbSavedFilterSnapshot, normalizeMlbSavedFilterSnapshot,
  NFL_SPORT_CONFIG, CFB_SPORT_CONFIG, MLB_SPORT_CONFIG,
} from './reducer.gen.mjs';

// Per-sport wiring: artifact + snapshot normalizer + engine config + how ctx lists are supplied.
const SPORTS: Record<string, {
  artifact: { systemPrompt: string; outputSchema: unknown };
  normalize: (raw: Record<string, unknown>) => Record<string, unknown>;
  config: unknown;
}> = {
  nfl: { artifact: artifactNfl, normalize: normalizeNflSavedFilterSnapshot, config: NFL_SPORT_CONFIG },
  cfb: { artifact: artifactCfb, normalize: normalizeCfbSavedFilterSnapshot, config: CFB_SPORT_CONFIG },
  mlb: { artifact: artifactMlb, normalize: normalizeMlbSavedFilterSnapshot, config: MLB_SPORT_CONFIG },
};

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Max-Age': '86400',
};

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } });

const SENTENCE_MAX = 500;

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });
  if (req.method !== 'POST') return json({ error: 'POST only' }, 405);

  try {
    // Require an authenticated user — this spends OpenAI credits, so it is not open to anonymous abuse.
    const authHeader = req.headers.get('Authorization') ?? '';
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_ANON_KEY')!,
      { global: { headers: { Authorization: authHeader } } },
    );
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return json({ error: 'unauthorized' }, 401);

    const body = await req.json().catch(() => null);
    const sentence = typeof body?.sentence === 'string' ? body.sentence.trim() : '';
    if (!sentence) return json({ error: 'sentence is required' }, 400);
    if (sentence.length > SENTENCE_MAX) return json({ error: `sentence exceeds ${SENTENCE_MAX} chars` }, 400);

    const sportKey = typeof body?.sport === 'string' ? body.sport : 'nfl';
    const sport = SPORTS[sportKey];
    if (!sport) return json({ error: `unknown sport "${sportKey}"` }, 400);
    const currentFilter = body?.currentFilter && typeof body.currentFilter === 'object' ? body.currentFilter : {};
    const strList = (v: unknown, cap = 200): string[] =>
      Array.isArray(v) ? v.filter((x: unknown) => typeof x === 'string').slice(0, cap) : [];
    const coaches = strList(body?.coaches);
    const referees = strList(body?.referees);
    const pitchers = strList(body?.pitchers, 2000);

    // Dedicated key for the trends/systems features (isolated usage + limits from the shared OPENAI_API_KEY).
    const openaiApiKey = Deno.env.get('TRENDS_OPENAI_API_KEY');
    if (!openaiApiKey) return json({ error: 'TRENDS_OPENAI_API_KEY not configured' }, 500);

    const userMessage = [
      `CURRENT FILTER (patch relative to this): ${JSON.stringify(currentFilter)}`,
      coaches.length ? `AVAILABLE COACHES (use exact spelling for a coach filter): ${coaches.join(', ')}` : '',
      referees.length ? `AVAILABLE REFEREES (use exact spelling for a referee filter): ${referees.join(', ')}` : '',
      pitchers.length ? `AVAILABLE PITCHERS (use exact spelling): ${pitchers.join(', ')}` : '',
      `USER REQUEST: ${sentence}`,
    ].filter(Boolean).join('\n\n');

    const openaiResponse = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: { Authorization: `Bearer ${openaiApiKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        temperature: 0, // deterministic extraction
        max_tokens: 900,
        messages: [
          { role: 'system', content: sport.artifact.systemPrompt },
          { role: 'user', content: userMessage },
        ],
        response_format: {
          type: 'json_schema',
          json_schema: { name: 'filter_patch', strict: true, schema: sport.artifact.outputSchema },
        },
      }),
    });

    if (!openaiResponse.ok) {
      const errText = await openaiResponse.text();
      console.error('OpenAI error:', errText);
      return json({ error: 'model request failed' }, 502);
    }

    const data = await openaiResponse.json();
    const content = data?.choices?.[0]?.message?.content;
    if (!content) return json({ error: 'empty model response' }, 502);

    // Structured Outputs guarantees valid JSON matching OUTPUT_SCHEMA.
    const parsed = JSON.parse(content);
    // Normalize the model's nullable fields into the reducer's op shape.
    const ops = Array.isArray(parsed.ops) ? parsed.ops.map((o: Record<string, unknown>) => {
      const op: Record<string, unknown> = { op: o.op, dimension: o.dimension };
      if (o.value !== null && o.value !== undefined) op.value = o.value;
      if (Array.isArray(o.items)) op.items = o.items;
      return op;
    }) : [];

    const couldnt_map = Array.isArray(parsed.couldnt_map) ? parsed.couldnt_map : [];
    const ambiguous = Array.isArray(parsed.ambiguous) ? parsed.ambiguous : [];

    // apply:true → validate + apply server-side (for clients without the TS reducer, i.e. iOS).
    // Returns the full validated snapshot (web tuple shape) + what happened, instead of raw ops.
    if (body?.apply === true) {
      const current = sport.normalize(currentFilter);
      const engineCtx = {
        lists: { coaches, referees },
        optionOverrides: pitchers.length ? { mlbPitchers: pitchers } : undefined,
      };
      // deno-lint-ignore no-explicit-any
      const result = applySportFilterPatch(sport.config as any, current, { ops }, engineCtx);
      return json({
        snapshot: result.snapshot,
        applied: result.applied,
        rejected: result.rejected.map((r: { reason: string }) => r.reason),
        noChange: result.noChange,
        couldnt_map, ambiguous,
      });
    }

    return json({ ops, couldnt_map, ambiguous });
  } catch (e) {
    console.error('nl-filter-patch error:', e);
    return json({ error: 'internal error' }, 500);
  }
});
