/** Exact Odds API school+mascot name -> app/ESPN school name. Port of iOS CFBSportsbookTeamAliases. */
export const CFB_SPORTSBOOK_ALIASES: Record<string, string> = {
  'Air Force Falcons': 'Air Force',
  'Akron Zips': 'Akron',
  'Alabama Crimson Tide': 'Alabama',
  'Appalachian State Mountaineers': 'App State',
  'Arizona State Sun Devils': 'Arizona State',
  'Arizona Wildcats': 'Arizona',
  'Arkansas Razorbacks': 'Arkansas',
  'Arkansas State Red Wolves': 'Arkansas State',
  'Army Black Knights': 'Army',
  'Auburn Tigers': 'Auburn',
  'Ball State Cardinals': 'Ball State',
  'Baylor Bears': 'Baylor',
  'Boise State Broncos': 'Boise State',
  'Boston College Eagles': 'Boston College',
  'Bowling Green Falcons': 'Bowling Green',
  'Buffalo Bulls': 'Buffalo',
  'BYU Cougars': 'BYU',
  'California Golden Bears': 'California',
  'Central Michigan Chippewas': 'Central Michigan',
  'Charlotte 49ers': 'Charlotte',
  'Cincinnati Bearcats': 'Cincinnati',
  'Clemson Tigers': 'Clemson',
  'Coastal Carolina Chanticleers': 'Coastal Carolina',
  'Colorado Buffaloes': 'Colorado',
  'Colorado State Rams': 'Colorado State',
  'Delaware Blue Hens': 'Delaware',
  'Duke Blue Devils': 'Duke',
  'East Carolina Pirates': 'East Carolina',
  'Eastern Michigan Eagles': 'Eastern Michigan',
  'Florida Atlantic Owls': 'Florida Atlantic',
  'Florida Gators': 'Florida',
  'Florida International Panthers': 'Florida International',
  'Florida State Seminoles': 'Florida State',
  'Fresno State Bulldogs': 'Fresno State',
  'Georgia Bulldogs': 'Georgia',
  'Georgia Southern Eagles': 'Georgia Southern',
  'Georgia State Panthers': 'Georgia State',
  'Georgia Tech Yellow Jackets': 'Georgia Tech',
  'Hawaii Rainbow Warriors': "Hawai'i",
  'Houston Cougars': 'Houston',
  'Idaho Vandals': 'Idaho',
  'Illinois Fighting Illini': 'Illinois',
  'Indiana Hoosiers': 'Indiana',
  'Iowa Hawkeyes': 'Iowa',
  'Iowa State Cyclones': 'Iowa State',
  'Jacksonville State Gamecocks': 'Jacksonville State',
  'James Madison Dukes': 'James Madison',
  'Kansas Jayhawks': 'Kansas',
  'Kansas State Wildcats': 'Kansas State',
  'Kennesaw State Owls': 'Kennesaw State',
  'Kent State Golden Flashes': 'Kent State',
  'Kentucky Wildcats': 'Kentucky',
  'Liberty Flames': 'Liberty',
  'Louisiana Ragin Cajuns': 'Louisiana',
  'Louisiana Tech Bulldogs': 'Louisiana Tech',
  'Louisville Cardinals': 'Louisville',
  'LSU Tigers': 'LSU',
  'Marshall Thundering Herd': 'Marshall',
  'Maryland Terrapins': 'Maryland',
  'Memphis Tigers': 'Memphis',
  'Miami (OH) RedHawks': 'Miami (OH)',
  'Miami Hurricanes': 'Miami',
  'Miami RedHawks': 'Miami (OH)',
  'Michigan State Spartans': 'Michigan State',
  'Michigan Wolverines': 'Michigan',
  'Middle Tennessee Blue Raiders': 'Middle Tennessee',
  'Minnesota Golden Gophers': 'Minnesota',
  'Mississippi Rebels': 'Ole Miss',
  'Mississippi State Bulldogs': 'Mississippi State',
  'Missouri State Bears': 'Missouri State',
  'Missouri Tigers': 'Missouri',
  'Navy Midshipmen': 'Navy',
  'NC State Wolfpack': 'NC State',
  'Nebraska Cornhuskers': 'Nebraska',
  'Nevada Wolf Pack': 'Nevada',
  'New Mexico Lobos': 'New Mexico',
  'New Mexico State Aggies': 'New Mexico State',
  'North Carolina Tar Heels': 'North Carolina',
  'North Dakota State Bison': 'North Dakota State',
  'North Texas Mean Green': 'North Texas',
  'Northern Illinois Huskies': 'Northern Illinois',
  'Northwestern Wildcats': 'Northwestern',
  'Notre Dame Fighting Irish': 'Notre Dame',
  'Ohio Bobcats': 'Ohio',
  'Ohio State Buckeyes': 'Ohio State',
  'Oklahoma Sooners': 'Oklahoma',
  'Oklahoma State Cowboys': 'Oklahoma State',
  'Old Dominion Monarchs': 'Old Dominion',
  'Ole Miss Rebels': 'Ole Miss',
  'Oregon Ducks': 'Oregon',
  'Oregon State Beavers': 'Oregon State',
  'Penn State Nittany Lions': 'Penn State',
  'Pittsburgh Panthers': 'Pittsburgh',
  'Purdue Boilermakers': 'Purdue',
  'Rice Owls': 'Rice',
  'Rutgers Scarlet Knights': 'Rutgers',
  'Sacramento State Hornets': 'Sacramento State',
  'Sam Houston State Bearkats': 'Sam Houston',
  'San Diego State Aztecs': 'San Diego State',
  'San Jose State Spartans': 'San José State',
  'SMU Mustangs': 'SMU',
  'South Alabama Jaguars': 'South Alabama',
  'South Carolina Gamecocks': 'South Carolina',
  'South Florida Bulls': 'South Florida',
  'Southern California Trojans': 'USC',
  'Southern Mississippi Golden Eagles': 'Southern Miss',
  'Stanford Cardinal': 'Stanford',
  'Syracuse Orange': 'Syracuse',
  'TCU Horned Frogs': 'TCU',
  'Temple Owls': 'Temple',
  'Tennessee Volunteers': 'Tennessee',
  'Texas A&M Aggies': 'Texas A&M',
  'Texas Longhorns': 'Texas',
  'Texas State Bobcats': 'Texas State',
  'Texas Tech Red Raiders': 'Texas Tech',
  'Toledo Rockets': 'Toledo',
  'Troy Trojans': 'Troy',
  'Tulane Green Wave': 'Tulane',
  'Tulsa Golden Hurricane': 'Tulsa',
  'UAB Blazers': 'UAB',
  'UCF Knights': 'UCF',
  'UCLA Bruins': 'UCLA',
  'UConn Huskies': 'UConn',
  'UL Monroe Warhawks': 'UL Monroe',
  'UMass Minutemen': 'Massachusetts',
  'UNLV Rebels': 'UNLV',
  'USC Trojans': 'USC',
  'Utah State Aggies': 'Utah State',
  'Utah Utes': 'Utah',
  'UTEP Miners': 'UTEP',
  'UTSA Roadrunners': 'UTSA',
  'Vanderbilt Commodores': 'Vanderbilt',
  'Virginia Cavaliers': 'Virginia',
  'Virginia Tech Hokies': 'Virginia Tech',
  'Wake Forest Demon Deacons': 'Wake Forest',
  'Washington Huskies': 'Washington',
  'Washington State Cougars': 'Washington State',
  'West Virginia Mountaineers': 'West Virginia',
  'Western Kentucky Hilltoppers': 'Western Kentucky',
  'Western Michigan Broncos': 'Western Michigan',
  'Wisconsin Badgers': 'Wisconsin',
  'Wyoming Cowboys': 'Wyoming',
};
