// Zod schemas for request/response validation
// and OpenAI structured output schema

import { z } from 'https://deno.land/x/zod@v3.22.4/mod.ts';

// =============================================================================
// Request Validation Schema
// =============================================================================

export const GeneratePicksRequestSchema = z.object({
  avatar_id: z.string().uuid('Invalid avatar_id format'),
  user_id: z.string().uuid('Invalid user_id format'),
  is_admin: z.boolean().optional().default(false),
});

export type GeneratePicksRequest = z.infer<typeof GeneratePicksRequestSchema>;

// =============================================================================
// AI Response Validation Schema (Zod)
// =============================================================================

export const GeneratedPickSchema = z.object({
  game_id: z.string().min(1, 'game_id is required'),
  bet_type: z.enum(['spread', 'moneyline', 'total']),
  selection: z.string().min(1, 'selection is required'),
  odds: z.string().regex(/^[+-]?\d+$/, 'odds must be in format like -110 or +150'),
  confidence: z.number().int().min(1).max(5),
  reasoning: z.string().min(50).max(300),
  key_factors: z.array(z.string().min(10).max(100)).min(3).max(5),
});

export const AIResponseSchema = z.object({
  picks: z.array(GeneratedPickSchema),
  slate_note: z.string().optional(),
});

export type GeneratedPick = z.infer<typeof GeneratedPickSchema>;
export type AIResponse = z.infer<typeof AIResponseSchema>;

// =============================================================================
// OpenAI Structured Output JSON Schema
// =============================================================================

export const AVATAR_PICKS_JSON_SCHEMA = {
  name: 'avatar_picks_response',
  strict: true,
  schema: {
    type: 'object',
    properties: {
      picks: {
        type: 'array',
        description: 'Array of betting picks generated by the agent. Provide 3-5 key_factors per pick.',
        items: {
          type: 'object',
          properties: {
            game_id: {
              type: 'string',
              description: 'Unique identifier for the game (training_key, unique_id, or game_id)',
            },
            bet_type: {
              type: 'string',
              enum: ['spread', 'moneyline', 'total'],
              description: 'Type of bet',
            },
            selection: {
              type: 'string',
              description: 'The specific pick (e.g., "Bills -1.5", "Chiefs ML", "Over 47.5")',
            },
            odds: {
              type: 'string',
              description: 'American odds format (e.g., "-110", "+150")',
            },
            confidence: {
              type: 'integer',
              description: 'Confidence level from 1 (low) to 5 (high)',
            },
            reasoning: {
              type: 'string',
              description: '2-3 sentences explaining why this pick was selected',
            },
            key_factors: {
              type: 'array',
              items: { type: 'string' },
              description: '3-5 key factors that support this pick',
            },
          },
          required: ['game_id', 'bet_type', 'selection', 'odds', 'confidence', 'reasoning', 'key_factors'],
          additionalProperties: false,
        },
      },
      slate_note: {
        type: 'string',
        description: 'A note about the overall slate quality or why certain picks were made/skipped',
      },
    },
    required: ['picks', 'slate_note'],
    additionalProperties: false,
  },
};

// =============================================================================
// Database Types
// =============================================================================

export interface AvatarProfile {
  id: string;
  user_id: string;
  name: string;
  avatar_emoji: string;  // Matches DB column name
  avatar_color: string;  // Matches DB column name
  preferred_sports: string[];
  archetype: string | null;
  personality_params: PersonalityParams;
  custom_insights: CustomInsights;
  is_public: boolean;
  is_active: boolean;
  auto_generate: boolean;
  last_generated_at: string | null;
  last_auto_generated_at: string | null;
  owner_last_active_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface PersonalityParams {
  // Core personality
  risk_tolerance: 1 | 2 | 3 | 4 | 5;
  underdog_lean: 1 | 2 | 3 | 4 | 5;
  over_under_lean: 1 | 2 | 3 | 4 | 5;
  confidence_threshold: 1 | 2 | 3 | 4 | 5;
  chase_value: boolean;

  // Bet selection
  preferred_bet_type: 'spread' | 'moneyline' | 'total' | 'any';
  max_favorite_odds: number | null;
  min_underdog_odds: number | null;
  max_picks_per_day: 1 | 2 | 3 | 4 | 5;
  skip_weak_slates: boolean;

  // Data trust
  trust_model: 1 | 2 | 3 | 4 | 5;
  trust_polymarket: 1 | 2 | 3 | 4 | 5;
  polymarket_divergence_flag: boolean;

  // NFL/CFB only
  fade_public?: boolean;
  public_threshold?: 1 | 2 | 3 | 4 | 5;
  weather_impacts_totals?: boolean;
  weather_sensitivity?: 1 | 2 | 3 | 4 | 5;

  // NBA/NCAAB only
  trust_team_ratings?: 1 | 2 | 3 | 4 | 5;
  pace_affects_totals?: boolean;

  // NBA only
  weight_recent_form?: 1 | 2 | 3 | 4 | 5;
  ride_hot_streaks?: boolean;
  fade_cold_streaks?: boolean;
  trust_ats_trends?: boolean;
  regress_luck?: boolean;

  // Situational
  home_court_boost: 1 | 2 | 3 | 4 | 5;
  fade_back_to_backs?: boolean;
  upset_alert?: boolean;
}

export interface CustomInsights {
  betting_philosophy?: string;
  perceived_edges?: string;
  avoid_situations?: string;
  target_situations?: string;
}

export interface AvatarPick {
  id?: string;
  avatar_id: string;
  game_id: string;
  sport: 'nfl' | 'cfb' | 'nba' | 'ncaab';  // Matches DB column name
  matchup: string;
  game_date: string;
  bet_type: 'spread' | 'moneyline' | 'total';
  pick_selection: string;  // Matches DB column name
  odds: string;
  units: number;
  confidence: number;
  reasoning_text: string;  // Matches DB column name
  key_factors: string[];
  archived_game_data: Record<string, unknown>;  // Matches DB column name
  archived_personality: PersonalityParams;  // Required by DB
  result: 'won' | 'lost' | 'push' | 'pending';  // Matches DB enum values
  actual_result?: string | null;
  graded_at?: string | null;
  created_at?: string;
}
