import SwiftUI
import UIKit
import WagerproofDesign
import WagerproofServices
import WagerproofStores
#if canImport(GoogleSignIn)
import GoogleSignIn
#endif

@main
struct WagerproofApp: App {
    @State private var authStore = AuthStore()
    @State private var rootRouter = RootRouter()
    @State private var onboardingStore = OnboardingStore()
    @State private var themeStore = ThemeStore()
    // B21 — global store for the Learn WagerProof walkthrough sheet. Injected
    // into the environment so any screen can call `learnStore.openSheet(...)`
    // and the sheet renders from MainTabView.
    @State private var learnStore = LearnWagerProofStore()
    // B08 — subscription / role / settings stores. RevenueCatStore bootstraps
    // the RevenueCat SDK on app launch; AdminModeStore queries `has_role`
    // whenever an authenticated user attaches; SettingsStore caches the
    // notification permission for the Settings toggles. ProAccessStore is a
    // thin facade that combines `RevenueCatStore + AdminModeStore` into a
    // single `isPro` answer. All four are individually injected into the
    // environment because views in the Settings + Paywall features read them
    // directly via `@Environment(...)`.
    //
    // No default initializers — each store is built exactly once in `init()`
    // so the ProAccessStore facade wraps the SAME instances that get injected
    // into the environment. SwiftUI's `@State` keeps them alive for the
    // lifetime of the App scene.
    @State private var revenueCatStore: RevenueCatStore
    @State private var adminModeStore: AdminModeStore
    @State private var settingsStore: SettingsStore
    @State private var proAccessStore: ProAccessStore
    // Global audit-store instance. RN provides this at the drawer layout level
    // so any descendant — including sport game-detail bottom sheets — can read
    // the currently-selected agent pick and render the inline rationale card.
    // See `Features/Agents/Components/AgentPickRationaleWidget.swift`.
    @State private var agentPickAuditStore = AgentPickAuditStore()
    #if DEBUG
    // DEBUG-only: backs the "Dummy Data Mode" toggle in Secret Settings.
    // Injected so SecretSettingsView can bind it and MainTabView can force a
    // Games reload when it flips. See `DummyDataMode` / `DummyData`.
    @State private var debugDataModeStore = DebugDataModeStore()
    #endif

    init() {
        // Configure Google Sign-In once at process launch — matches the RN
        // configureGoogleSignIn() call in contexts/AuthContext.tsx.
        GoogleSignInCoordinator.configureIfNeeded()
        // Boot the Meta SDK so CompleteRegistration / Subscribe events have a
        // configured AppEvents pipeline by the time onboarding / paywall fires.
        // Auto-logging is OFF inside the service to avoid double-counting with
        // RevenueCat's server-side Meta CAPI integration.
        MetaAnalyticsService.shared.initialize()
        // Phase 2: bootstrap analytics with the real Mixpanel token from a
        // Secrets.swift generated by `scripts/generate-secrets.sh`. The token
        // mirrors the RN app's `EXPO_PUBLIC_MIXPANEL_TOKEN`.

        // Build the subscription stores up-front so the ProAccessStore facade
        // can wrap the SAME instances we'll also inject into the environment.
        let rc = RevenueCatStore()
        let admin = AdminModeStore()
        _revenueCatStore = State(initialValue: rc)
        _adminModeStore = State(initialValue: admin)
        _settingsStore = State(initialValue: SettingsStore())
        _proAccessStore = State(initialValue: ProAccessStore(revenueCat: rc, adminMode: admin))
    }

    var body: some Scene {
        WindowGroup {
            #if DEBUG
            if ScreenshotHarness.isActive {
                ScreenshotHarnessView()
            } else {
                productionRoot
            }
            #else
            productionRoot
            #endif
        }
    }

    @ViewBuilder
    private var productionRoot: some View {
        RootView()
            .environment(authStore)
            .environment(rootRouter)
            .environment(onboardingStore)
            .environment(themeStore)
            .environment(learnStore)
            .environment(revenueCatStore)
            .environment(adminModeStore)
            .environment(settingsStore)
            .environment(proAccessStore)
            .environment(agentPickAuditStore)
            #if DEBUG
            .environment(debugDataModeStore)
            #endif
            .preferredColorScheme(themeStore.mode.colorScheme)
            // `.preferredColorScheme` only governs the SwiftUI hierarchy it's
            // attached to; our color tokens are dynamic `UIColor { trait }`
            // values keyed to the window's `userInterfaceStyle`, and sheets /
            // covers live in their own presentation contexts. Forcing the
            // override on every window flips all of them — and the dynamic
            // colors inside them — in one pass, so a theme toggle repaints the
            // whole app at once instead of piecemeal.
            .onChange(of: themeStore.mode, initial: true) { _, mode in
                applyInterfaceStyle(mode)
            }
            .task {
                authStore.start()
                // Bootstrap RevenueCat immediately so the SDK can resolve
                // entitlements before the first Pro-gated screen renders.
                // The attach call below kicks in once auth flips to
                // .authenticated; bootstrap is auth-agnostic and idempotent.
                revenueCatStore.bootstrap()
            }
            .onChange(of: authStore.phase) { _, newPhase in
                // Attach onboarding BEFORE router resolves so the per-user
                // cache is loaded synchronously — otherwise the router sees
                // `isComplete=false` and renders OnboardingView for a frame
                // before the second .onChange below flips it to .ready.
                if case .authenticated(let userId) = newPhase {
                    onboardingStore.attachUser(userId: userId.uuidString)
                } else if case .unauthenticated = newPhase {
                    onboardingStore.detachUser()
                }
                rootRouter.resolve(
                    authPhase: newPhase,
                    onboardingComplete: onboardingStore.isComplete
                )
                Task {
                    await handleAuthPhaseChange(newPhase)
                }
            }
            .onChange(of: onboardingStore.isComplete) { _, _ in
                rootRouter.resolve(
                    authPhase: authStore.phase,
                    onboardingComplete: onboardingStore.isComplete
                )
            }
            .onOpenURL { url in
                // Meta SDK gets first look — ad-network / app-switch callbacks
                // (fbauth2, fb-messenger-share-api, etc.) must reach FBSDK
                // before any other router or they won't attribute correctly.
                if MetaAnalyticsService.shared.handleAppDelegate(url: url) { return }
                #if canImport(GoogleSignIn)
                // Route Google OAuth callback URLs next; if GIDSignIn doesn't
                // claim it, fall through to the deep-link router.
                if GIDSignIn.sharedInstance.handle(url) { return }
                #endif
                rootRouter.handle(deepLink: url)
            }
    }

    /// Push the chosen theme onto every live window's
    /// `overrideUserInterfaceStyle` so all presentation contexts (root, sheets,
    /// covers) — and the dynamic `UIColor` tokens they render — switch
    /// simultaneously. `.system` clears the override back to `.unspecified`.
    private func applyInterfaceStyle(_ mode: ThemeStore.Mode) {
        let style: UIUserInterfaceStyle = switch mode {
        case .system: .unspecified
        case .light: .light
        case .dark: .dark
        }
        for scene in UIApplication.shared.connectedScenes {
            guard let windowScene = scene as? UIWindowScene else { continue }
            for window in windowScene.windows {
                window.overrideUserInterfaceStyle = style
            }
        }
    }

    /// Wire the subscription + role stores to Supabase auth changes.
    /// `.authenticated` → identify with RC + run the admin role check.
    /// `.unauthenticated` → log out of RC + clear admin state. Mirrors RN's
    /// useEffect in RevenueCatContext.tsx that watches `user?.id`.
    private func handleAuthPhaseChange(_ phase: AuthStore.Phase) async {
        // Onboarding attach/detach is handled synchronously in the .onChange
        // handler above (must run before rootRouter.resolve). This async path
        // is only for the network-bound RC + role calls.
        switch phase {
        case .authenticated(let userId):
            await revenueCatStore.attachUser(userId)
            await adminModeStore.checkRole(for: userId)
        case .unauthenticated:
            await revenueCatStore.detachUser()
            adminModeStore.reset()
        case .launching:
            break
        }
    }
}
