#!/usr/bin/env python3
"""COMBO CONSISTENCY: price the combo market against its own components.

Every NBA edge this project has ever validated lives in a DERIVATIVE market, never the
main one. S7 (1H total) and S8 (1H spread) both survived where the full-game versions of
the same idea died, because the full-game market is where the money and the correction
are, and the derivative is priced off it by a rule.

Player props have exactly that structure and nobody has pointed at it yet. The book posts
points, rebounds and assists for a player -- and it separately posts points+rebounds+
assists. PRA is not an independent opinion. It is a derivative of the other three, and it
has to be generated by some rule that combines them.

So: reconstruct the combo line from its components and bet the disagreement.

THE NUISANCE PARAMETER. You cannot simply compare line(PRA) to line(pts)+line(reb)+
line(ast). A posted line sits near a MEDIAN, and the median of a sum is not the sum of
medians for skewed counts -- there is a systematic offset, and it differs per combo and
drifts with scoring environment. Treating that offset as signal would produce a huge fake
edge pointing the same way on every prop.

So the offset is estimated as a nuisance parameter, WALK-FORWARD, from strictly earlier
games only, per combo market. The bet is on the RESIDUAL: how far this prop's gap sits
from the gap the book normally runs. That makes the test about inconsistency, not about
the shape of the sum.

Deliberately MODEL-FREE. No booster, no features, no fitted distribution -- only lines
the book itself posted at the same T-60 snapshot. If an edge shows up here it cannot be
an artifact of my feature engineering, which makes it much stronger evidence than
anything in the model runs. It is also instantly executable: it needs no data at bet time
beyond the book's own screen.

Graded at each market's own consensus line and price. Pushes dropped.
"""
import os
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(ROOT, "data", "parquet")

# combo market -> the component markets it decomposes into
COMBOS = {
    "player_points_rebounds_assists": ["player_points", "player_rebounds",
                                       "player_assists"],
    "player_points_rebounds": ["player_points", "player_rebounds"],
    "player_points_assists": ["player_points", "player_assists"],
    "player_rebounds_assists": ["player_rebounds", "player_assists"],
}


def roi(win, dec):
    return 100 * (win * (dec - 1) - (1 - win)).mean()


def grade(d, side_over, line_col="cons_line"):
    """Grade at the combo's own consensus line and price. Pushes dropped."""
    live = d["actual"] != d[line_col]
    d = d[live]
    if len(d) < 60:
        return 0, np.nan, np.nan
    ow = (d["actual"] > d[line_col]).to_numpy(dtype=float)
    win = ow if side_over else 1 - ow
    dec = (d["cons_over_dec"] if side_over else d["cons_under_dec"]).to_numpy(dtype=float)
    g = ~np.isnan(dec)
    if g.sum() < 60:
        return 0, np.nan, np.nan
    return int(g.sum()), 100 * win[g].mean(), roi(win[g], dec[g])


def build():
    """One row per (player, game, combo) carrying the combo line and its component sum."""
    D = pd.read_parquet(f"{OUT}/nba_props_panel.parquet").rename(
        columns={"season_x": "season"})
    D["date"] = pd.to_datetime(D["date"])
    keep = ["event_id", "pkey", "market", "date", "season", "cons_line", "cons_over_dec",
            "cons_under_dec", "cons_p_over", "actual", "gp_prior"]
    D = D[[c for c in keep if c in D.columns]].dropna(subset=["cons_line"])

    # wide: one row per player-game, one column per market's line
    W = D.pivot_table(index=["event_id", "pkey", "date", "season"], columns="market",
                      values="cons_line", aggfunc="first")
    W.columns = [f"ln_{c}" for c in W.columns]
    W = W.reset_index()

    frames = []
    for combo, parts in COMBOS.items():
        need = [f"ln_{p}" for p in parts]
        if any(n not in W.columns for n in need) or f"ln_{combo}" not in W.columns:
            continue
        w = W[["event_id", "pkey", "date", "season", f"ln_{combo}"] + need].dropna()
        w = w.rename(columns={f"ln_{combo}": "combo_line"})
        w["parts_sum"] = w[need].sum(axis=1)
        w["gap"] = w["combo_line"] - w["parts_sum"]
        w["market"] = combo
        # attach the combo's own price + settled result
        C = D[D["market"] == combo][["event_id", "pkey", "cons_line", "cons_over_dec",
                                     "cons_under_dec", "cons_p_over", "actual",
                                     "gp_prior"]]
        w = w.merge(C, on=["event_id", "pkey"], how="inner")
        frames.append(w)
    P = pd.concat(frames, ignore_index=True).sort_values("date").reset_index(drop=True)
    return P[P["gp_prior"] >= 5].reset_index(drop=True)


def add_expected_gap(P, halflife_days=45):
    """Walk-forward estimate of the gap the book NORMALLY runs, per combo market.

    Strictly-earlier-only: an expanding mean over prior games, so nothing about today's
    slate informs today's reference. Requires a minimum history before it will score a
    row at all -- an early-season reference built on 40 props is noise, and betting the
    residual against noise is just betting noise twice.
    """
    P = P.sort_values(["market", "date"]).copy()
    P["exp_gap"] = np.nan
    P["gap_n"] = np.nan
    for mk, idx in P.groupby("market").groups.items():
        s = P.loc[idx].copy()
        # daily mean gap, then an expanding mean over STRICTLY EARLIER days
        daily = s.groupby("date")["gap"].mean()
        prior_mean = daily.shift(1).expanding().mean()
        prior_n = daily.shift(1).expanding().count()
        P.loc[idx, "exp_gap"] = s["date"].map(prior_mean)
        P.loc[idx, "gap_n"] = s["date"].map(prior_n)
    P["resid"] = P["gap"] - P["exp_gap"]
    return P


def main():
    print("building combo panel...", flush=True)
    P = build()
    P = add_expected_gap(P)
    P = P[P["gap_n"] >= 20]                      # 20 prior slates of reference minimum
    seasons = sorted(P["season"].dropna().unique())
    print(f"  {len(P):,} combo props with a usable reference", flush=True)

    L = ["# NBA props — combo markets against their own components", "",
         f"{len(P):,} combo props, seasons {seasons}, consensus lines at T-60. "
         "Model-free: the only inputs are lines the book posted itself.", "",
         "`gap` = combo line minus the sum of its component lines. `resid` = that gap "
         "minus the gap this market normally runs, estimated walk-forward from strictly "
         "earlier slates. A POSITIVE resid means the combo line is set high relative to "
         "its own components, which argues the UNDER.", ""]

    L += ["\n## The nuisance parameter itself (why the raw gap cannot be the signal)\n",
          "| market | n | mean gap | sd of gap | mean |resid| |", "|---|---|---|---|---|"]
    for mk in sorted(P["market"].unique()):
        s = P[P["market"] == mk]
        L.append(f"| {mk} | {len(s):,} | {s['gap'].mean():+.2f} | {s['gap'].std():.2f} "
                 f"| {s['resid'].abs().mean():.2f} |")

    # ------------------------------------------------------------------ the actual test
    L += ["\n## Bet the residual\n",
          "| resid | side | n | win% | ROI | per-season ROI |", "|---|---|---|---|---|---|"]
    bands = ((0.25, 0.75, "0.25-0.75"), (0.75, 1.25, "0.75-1.25"),
             (1.25, 2.0, "1.25-2.0"), (2.0, 99, "2.0+"))
    for lo, hi, lbl in bands:
        # combo line set HIGH vs its components -> under
        s = P[(P["resid"] >= lo) & (P["resid"] < hi)]
        n, w, r = grade(s, False)
        per = [f"{grade(s[s['season'] == ss], False)[2]:+.1f}" for ss in seasons]
        L.append(f"| +{lbl} | under | {n:,} | {w:.2f} | {r:+.2f} | {'/'.join(per)} |")
        # combo line set LOW vs its components -> over
        s = P[(P["resid"] <= -lo) & (P["resid"] > -hi)]
        n, w, r = grade(s, True)
        per = [f"{grade(s[s['season'] == ss], True)[2]:+.1f}" for ss in seasons]
        L.append(f"| -{lbl} | over | {n:,} | {w:.2f} | {r:+.2f} | {'/'.join(per)} |")

    # ---------------------------------------------------- control: is it just the shade?
    # The under side of any prop test is flattered by the standing over-shade. If the
    # residual carries information, the UNDER cells must beat blind under on the same
    # market, and the OVER cells must beat blind over. Comparing to 50% would be a lie.
    L += ["\n## Control — against blind side-betting on the same markets\n",
          "| bet | n | win% | ROI |", "|---|---|---|---|"]
    for nm, so in (("blind UNDER, all combo props", False),
                   ("blind OVER, all combo props", True)):
        n, w, r = grade(P, so)
        L.append(f"| {nm} | {n:,} | {w:.2f} | {r:+.2f} |")

    L += ["\n## Per market, |resid| >= 0.75\n",
          "| market | side | n | win% | ROI | blind same-side ROI | delta |",
          "|---|---|---|---|---|---|---|"]
    for mk in sorted(P["market"].unique()):
        m = P[P["market"] == mk]
        _, _, bu = grade(m, False)
        _, _, bo = grade(m, True)
        for side, so, sel, base in (("under", False, m["resid"] >= 0.75, bu),
                                    ("over", True, m["resid"] <= -0.75, bo)):
            n, w, r = grade(m[sel], so)
            d = r - base if pd.notna(r) else np.nan
            L.append(f"| {mk} | {side} | {n:,} | {w:.2f} | {r:+.2f} | {base:+.2f} | "
                     f"{d:+.2f} |")

    # ------------------------------------------------- does it survive the vig at scale?
    L += ["\n## Monotonicity — |resid| ladder, both sides pooled\n",
          "| |resid| >= | n | win% | ROI | delta vs blind same-side |",
          "|---|---|---|---|---|"]
    _, _, bu = grade(P, False)
    _, _, bo = grade(P, True)
    for t in (0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0):
        u = P[P["resid"] >= t] if t > 0 else P[P["resid"] >= 0]
        o = P[P["resid"] <= -t] if t > 0 else P[P["resid"] < 0]
        nu, wu, ru = grade(u, False)
        no, wo, ro = grade(o, True)
        n = nu + no
        if n == 0:
            continue
        win = (wu * nu + wo * no) / n
        r = (ru * nu + ro * no) / n
        base = (bu * nu + bo * no) / n
        L.append(f"| {t:.2f} | {n:,} | {win:.2f} | {r:+.2f} | {r-base:+.2f} |")

    P.to_parquet(f"{OUT}/nba_props_combo_scored.parquet", index=False)
    path = os.path.join(ROOT, "NBA_PROPS_COMBO_BRIEF.md")
    with open(path, "w") as f:
        f.write("\n".join(L) + "\n")
    print("\n".join(L), flush=True)
    print(f"wrote {path}", flush=True)


if __name__ == "__main__":
    main()
