import React from 'react';
import { Link } from 'react-router-dom';
import { ChevronLeft } from 'lucide-react';
import { SEO } from '@/components/landing/SEO';

const TermsAndConditions = () => {
  return (
    <>
      <SEO
        title="Terms and Conditions"
        description="Read WagerProof's terms and conditions. Understand our service disclaimers, user responsibilities, and legal agreements for using our sports betting analytics platform."
        canonical="https://www.wagerproof.bet/terms-and-conditions"
      />
      <div className="container mx-auto px-4 py-8 max-w-3xl">
      <div className="flex items-center mb-6">
        <Link to="/" className="text-muted-foreground hover:text-primary flex items-center">
          <ChevronLeft className="h-4 w-4 mr-1" /> Back to Home
        </Link>
      </div>
      <h1 className="text-4xl font-extrabold mb-6 text-primary">Terms and Conditions for WagerProof</h1>
      <p className="text-sm text-muted-foreground mb-8">**Last Updated: October 15, 2025**</p>

      <h2 className="text-2xl font-bold mb-4 text-primary">1. Acceptance of the Terms of Service</h2>
      <p className="mb-4">These terms and conditions of service are entered into by and between you and WagerProof LLC, a Texas limited liability company ("WagerProof," "Company," "we," or "us"). The following terms and conditions of service, together with any documents they expressly incorporate by reference (collectively, "Terms of Service"), govern your access to and use of https://wagerproof.bet (the "Website"), including any content, functionality, and services offered on or through the Website, whether as a guest or a registered user, (collectively, the "Services").</p>
      <p className="mb-4">Please read the Terms of Service carefully before you start to use the Services. By clicking "I Accept," creating an account, accessing, or using the Services in any manner, you acknowledge that you have read, understood, and agree to be bound and abide by these Terms of Service, including our Privacy Policy, found at https://wagerproof.bet/privacy-policy, which is hereby incorporated herein by reference. If you do not agree to these Terms of Service, you are not authorized to access or use the Services and must immediately cease all use of the Services.</p>

      <h2 className="text-2xl font-bold mb-4 text-primary">2. Nature of Service & Disclaimers</h2>
      <ul className="list-disc pl-5 mb-4 space-y-2">
        <li><strong>Sports Data Analytics Only</strong>: WagerProof provides data-driven sports insights, statistical analysis, and educational tools through proprietary machine learning models and algorithms. The Services offer statistical models, trend analysis, predictive analytics, and data visualizations to assist users in making informed decisions. All content is for informational and educational purposes only.</li>
        <li><strong>NOT Financial or Betting Advice</strong>: <strong>WagerProof DOES NOT provide financial advice, investment advice, or direct betting recommendations, whether through the Services or otherwise.</strong> The information, data, analytics, and tools provided through the Services are for informational, educational, and entertainment purposes only. You should not consider any materials provided on or through the Services as a solicitation, recommendation, offer, or endorsement to place any wagers or engage in any gambling activity. You should consult with qualified professionals regarding your specific circumstances before making any betting or financial decisions.</li>
        <li><strong>NO GUARANTEES OF ACCURACY OR OUTCOMES</strong>: <strong>WE MAKE NO GUARANTEES, REPRESENTATIONS, OR WARRANTIES REGARDING THE ACCURACY, RELIABILITY, OR COMPLETENESS OF OUR DATA, ANALYTICS, PREDICTIONS, OR MODELS. WE DO NOT GUARANTEE ANY PROFITS, WINNINGS, POSITIVE OUTCOMES, OR SPECIFIC RESULTS FROM USING OUR SERVICES. SPORTS OUTCOMES ARE INHERENTLY UNPREDICTABLE AND INVOLVE SUBSTANTIAL RISK OF LOSS. PAST PERFORMANCE OF OUR MODELS OR PREDICTIONS IS NOT INDICATIVE OF FUTURE RESULTS. YOU MAY LOSE MONEY BY RELYING ON OUR SERVICES.</strong></li>
        <li><strong>USER RESPONSIBILITY AND ASSUMPTION OF RISK</strong>: <strong>YOU ARE SOLELY AND EXCLUSIVELY RESPONSIBLE FOR YOUR OWN DECISIONS, ACTIONS, AND ANY FINANCIAL GAINS OR LOSSES INCURRED. YOU ACKNOWLEDGE AND EXPRESSLY AGREE THAT: (A) YOU USE THE SERVICES ENTIRELY AT YOUR OWN RISK; (B) YOU HAVE CONDUCTED YOUR OWN INDEPENDENT RESEARCH AND ANALYSIS; (C) YOU ARE NOT RELYING SOLELY ON WAGERPROOF'S DATA OR ANALYTICS; (D) YOU UNDERSTAND THE RISKS ASSOCIATED WITH SPORTS BETTING AND GAMBLING; AND (E) YOU HAVE THE FINANCIAL MEANS TO ABSORB ANY LOSSES YOU MAY INCUR. YOU HEREBY RELEASE AND HOLD HARMLESS WAGERPROOF FROM ANY AND ALL CLAIMS ARISING FROM YOUR USE OF THE SERVICES OR ANY BETTING ACTIVITIES.</strong></li>
        <li><strong>NOT A GAMBLING OPERATOR</strong>: <strong>WAGERPROOF IS NOT A BOOKMAKER, CASINO, GAMBLING OPERATOR, SPORTSBOOK, OR A PLATFORM FOR PLACING BETS. WE DO NOT ACCEPT, PROCESS, FACILITATE, OR HAVE ANY INVOLVEMENT IN WAGERS, BETS, OR GAMBLING TRANSACTIONS OF ANY KIND. WE DO NOT HOLD ANY GAMBLING LICENSES OR PERMITS. WAGERPROOF IS SOLELY A DATA ANALYTICS AND INFORMATION SERVICES PROVIDER. WAGERPROOF DOES NOT CONDONE ILLEGAL GAMBLING.</strong></li>
      </ul>
      <p className="mb-4">The information and materials presented on or through the Services are made available solely for general information, educational, and entertainment purposes. We do not warrant the accuracy, completeness, or usefulness of this information. Any reliance you place on such information is strictly at your own risk. We disclaim all liability and responsibility arising from any reliance placed on such materials by you or any other user of the Services, or by anyone who may be informed of any of its contents.</p>
      <p className="mb-4">The Services may include content provided by third parties, including materials provided by other users, third-party licensors, syndicators, aggregators, and/or reporting services. All statements and/or opinions expressed in these materials, and all articles and responses to questions and other content, other than the content created and provided by WagerProof, are solely the opinions and the responsibility of the person or entity providing those materials. These materials do not necessarily reflect the opinion of the Company. We are not responsible, or liable to you or any third party, for the content or accuracy of any materials provided by any third parties.</p>
      <p className="mb-4">You understand that we cannot and do not guarantee or warrant that files available for downloading from the internet or the Services will be free of viruses or other destructive code. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for anti-virus protection and accuracy of data input and output, and for maintaining a means external to our systems for any reconstruction of any lost data. <strong>TO THE FULLEST EXTENT PROVIDED BY LAW, WAGERPROOF WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY A DISTRIBUTED DENIAL-OF-SERVICE ATTACK, VIRUSES, OR OTHER TECHNOLOGICALLY HARMFUL MATERIAL THAT MAY INFECT YOUR ELECTRONIC DEVICES, SOFTWARE PROGRAMS, DATA, OR OTHER PROPRIETARY MATERIAL DUE TO YOUR USE OF THE SERVICES OR ANY MATERIALS OBTAINED THROUGH THE SERVICES OR YOUR DOWNLOADING OF ANY MATERIAL POSTED ON THEM, OR ON ANY PLATFORM LINKED TO THEM.</strong></p>
      <p className="mb-4"><strong>YOUR USE OF THE SERVICES, ITS CONTENT, AND ANY SERVICES OR MATERIALS OBTAINED THROUGH THE SERVICES IS AT YOUR OWN RISK. THE SERVICES, ITS CONTENT, AND ANY SERVICES OR MATERIALS OBTAINED THROUGH THEM ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. NEITHER THE WAGERPROOF NOR ANY PERSON ASSOCIATED WITH THE COMPANY MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY, ACCURACY, OR AVAILABILITY OF THE SERVICES. WITHOUT LIMITING THE FOREGOING, NEITHER WAGERPROOF NOR ANYONE ASSOCIATED WITH THE COMPANY REPRESENTS OR WARRANTS THAT THE SERVICES, ITS CONTENT, OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE SERVICES WILL BE ACCURATE, RELIABLE, ERROR-FREE, OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, THAT THE SERVICES OR THE SERVER(S) THAT MAKES THEM AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, OR THAT THE SERVICES OR ANY SERVICES OR MATERIALS OBTAINED THROUGH THE SERVICES WILL OTHERWISE MEET YOUR NEEDS OR EXPECTATIONS.</strong></p>
      <p className="mb-4"><strong>TO THE FULLEST EXTENT PROVIDED BY LAW, THE WAGERPROOF HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, AND FITNESS FOR PARTICULAR PURPOSE.</strong></p>
      <p className="mb-4">THE FOREGOING DOES NOT AFFECT ANY WARRANTIES THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.</p>

      <h2 className="text-2xl font-bold mb-4 text-primary">3. Accessing Services and Account Security</h2>
      <p className="mb-4">The Services are offered and available only to users who are 18 years of age or older, and reside in the United States or any of its territories or possessions. By using the Services, you represent and warrant that you are of legal age to form a binding contract with the Company and meet all of the foregoing eligibility requirements. You further warrant that you are legally permitted to access the Services in your jurisdiction. If you do not meet all of these requirements, you must not create an account or access or use the Services.</p>
      <p className="mb-4">We reserve the right to withdraw or amend the Services, and any service or material we provide through the Services, in our sole discretion without notice. We will not be liable if for any reason all or any part of the Services are unavailable at any time or for any period. From time to time, we may restrict user access, including registered user access, to parts, or all, of the Services.</p>
      <p className="mb-4">To access the Services or some of the resources they offer, you may be asked to provide certain registration details or other information. It is a condition of your use of the Services that all the information you provide is correct, current, and complete. You agree that all information you provide to register with the Services or otherwise, including, but not limited to, through the use of any interactive features on the Services, is governed by our Privacy Policy, and you consent to all actions we take with respect to your information consistent with our Privacy Policy.</p>
      <p className="mb-4">If you choose, or are provided with, a username, password, or any other piece of information as part of our security procedures, you must treat such information as confidential, and you must not disclose it to any other person or entity. You also acknowledge that your account is personal to you and agree not to provide any other person with access to the Services, or portions thereof, using your username, password, or other security information. You shall be responsible for all activities conducted through your account, whether authorized by you or not, until you notify us of unauthorized access. You agree to notify us immediately of any unauthorized access to or use of your username or password or any other breach of security. You also agree to ensure that you exit from your account at the end of each session. You should use particular caution when accessing your account from a public or shared computer so that others are not able to view or record your password or other personal information.</p>
      <p className="mb-4">We have the right to disable any username, password, or other identifier, whether chosen by you or provided by us, at any time in our sole discretion for any or no reason, including if, in our opinion, you have violated any provision of these Terms of Service.</p>

      <h2 className="text-2xl font-bold mb-4 text-primary">4. Subscriptions and Payments</h2>
      <ul className="list-disc pl-5 mb-4 space-y-2">
        <li><strong>Subscription Plans</strong>: We offer various subscription plans (e.g., Basic, Pro, Enterprise) with different features and pricing. Details of these plans are available on our website, at [include link to applicable webpage].</li>
        <li><strong>Billing</strong>: Subscriptions are billed on a recurring basis (e.g., monthly or annually) through our third-party payment processor, Stripe. By subscribing, you authorize us and Stripe to charge your designated payment method at the beginning of each billing cycle. You acknowledge that the amount billed may vary from cycle to cycle if you change your subscription plan or if applicable taxes change, and you authorize us to charge your payment method for such varying amounts.</li>
        <li><strong>Price Changes</strong>: We reserve the right to change our subscription fees at any time. Any price changes will be communicated to you in advance, and you will have the option to cancel your subscription before the new prices take effect, and such cancellation will be effective at the end of your current billing period.</li>
        <li><strong>Cancellations and Refunds</strong>: You may cancel your subscription at any time by accessing your account settings or contacting customer support at [INSERT CONTACT EMAIL]. Cancellations will take effect at the end of your current billing period, and you will retain access to the Services until that time. We do not offer refunds for partial subscription periods, except (i) as expressly provided in these Terms of Service, (ii) in cases of material breach by WagerProof, or (iii) as may be required by applicable law.</li>
        <li><strong>Promotions and Trials</strong>: We may offer promotional pricing or free trial periods. These are subject to specific terms and conditions that will be provided at the time of the offer. We reserve the right to modify or terminate promotional offers at any time, provided that any such modification or termination shall not affect promotional pricing or trial periods already granted to users. Free trial users may be automatically enrolled in a paid subscription at the end of the trial period unless they cancel before the trial expires.</li>
      </ul>
      <p className="mb-4">All purchases of subscriptions or other transactions for the sale of services or information carried out through the Services are governed by our Terms of Sale [LINK TO TERMS OF SALE], which are hereby incorporated by reference into these Terms of Service. The Terms of Sale shall control with respect to purchase-related matters.</p>
      <p className="mb-4">Additional terms and conditions may also apply to specific portions, services, or features of the Services. All such additional terms and conditions are hereby incorporated by this reference into these Terms of Service.</p>

      <h2 className="text-2xl font-bold mb-4 text-primary">5. Prohibited Uses</h2>
      <p className="mb-2">You may use the Services only for lawful purposes and in accordance with these Terms of Service. You agree not to use the Services:</p>
      <ul className="list-disc pl-5 mb-4 space-y-2">
        <li>In any way that violates any applicable federal, state, local, or international law or regulation (including, without limitation, any laws regarding the export of data or software to and from the US or other countries, any gambling laws or regulations, or any laws regarding the use of data for illegal gambling activities).</li>
        <li>For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content, asking for personally identifiable information, or otherwise.</li>
        <li>To transmit, or procure the sending of, any advertising or promotional material, including any "junk mail," "chain letter," "spam," or any other similar solicitation.</li>
        <li>To impersonate or attempt to impersonate WagerProof, a Company employee, another user, or any other person or entity (including, without limitation, by using email addresses or usernames associated with any of the foregoing).</li>
        <li>To engage in any other conduct that restricts or inhibits anyone's use or enjoyment of the Services, or which, as determined by us, may harm WagerProof or users of the Services, or expose them to liability. Prohibited conduct includes, but is not limited to, using the Services or any data obtained therefrom for any illegal gambling activities, money laundering, fraud, or any activity that violates applicable gaming or gambling regulations.</li>
      </ul>
      <p className="mb-2">Additionally, you agree not to:</p>
      <ul className="list-disc pl-5 mb-4 space-y-2">
        <li>Use the Services in any manner that could disable, overburden, damage, or impair the Services or interfere with any other party's use of the Services, including their ability to engage in real time activities through the Services. This includes, without limitation, using any automated systems, bots, or scraping tools to access, collect, or download data from the Services, except as expressly authorized in writing by WagerProof.</li>
        <li>Use any robot, spider, or other automatic device, process, or means to access the Services for any purpose, including monitoring or copying any of the material provided through the Services.</li>
        <li>Use any manual process to monitor or copy any of the material on or provided through the Services in any manner that exceeds normal individual use, or for any other purpose not expressly authorized in these Terms of Service, without our prior written consent.</li>
        <li>Use any device, software, or routine that interferes with the proper working of the Services.</li>
        <li>Introduce any viruses, Trojan horses, worms, logic bombs, or other material that is malicious or technologically harmful.</li>
        <li>Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the Services, the server on which the Services are stored or run, or any server, computer, or database connected to the Services.</li>
        <li>Attack the Services via a denial-of-service attack or a distributed denial-of-service attack.</li>
        <li>Otherwise attempt to interfere with the proper working of the Services.</li>
      </ul>

      <h2 className="text-2xl font-bold mb-4 text-primary">6. Monitoring and Enforcement; Termination</h2>
      <p className="mb-4">We have the right to:</p>
      <ul className="list-disc pl-5 mb-4 space-y-2">
        <li>Take appropriate legal action, including without limitation, referral to law enforcement, for any illegal or unauthorized use of the Services.</li>
        <li>Terminate or suspend your access to all or part of the Services for any or no reason, including without limitation, any violation of these Terms of Service.</li>
      </ul>
      <p className="mb-4">Without limiting the foregoing, we have the right to cooperate fully with any law enforcement authorities or court order requesting or directing us to disclose the identity or other information of anyone using the Services. <strong>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, YOU AGREE TO WAIVE AND HOLD HARMLESS THE COMPANY AND ITS AFFILIATES, LICENSEES, AND SERVICE PROVIDERS FROM ANY CLAIMS RESULTING FROM ANY ACTION TAKEN BY ANY OF THE FOREGOING PARTIES DURING, OR TAKEN AS A CONSEQUENCE OF, INVESTIGATIONS BY EITHER SUCH PARTIES OR LAW ENFORCEMENT AUTHORITIES.</strong></p>
      <p className="mb-4">We do not undertake to review all material before it is posted on the Services and cannot ensure prompt removal of objectionable material after it has been posted. Accordingly, to the maximum extent permitted by law, we assume no liability for any action or inaction regarding transmissions, communications, or content provided by any user of the Services or third party, except as required by applicable law. We have no liability or responsibility to anyone for performance or nonperformance of the activities described in this section, except where such liability cannot be excluded by law.</p>

      <h2 className="text-2xl font-bold mb-4 text-primary">7. Links</h2>
      <p className="mb-4">If the Services contains links to other resources provided by third parties, these links are provided for your convenience only. This includes links contained in advertisements, including banner advertisements and sponsored links. We have no control over the contents of those sites or resources and, to the maximum extent permitted by law, accept no responsibility for them or for any loss or damage that may arise from your use of them. If you decide to access any of the third-party platforms linked to the Services, you do so entirely at your own risk and subject to the terms and conditions of use for such platforms.</p>

      <h2 className="text-2xl font-bold mb-4 text-primary">8. Intellectual Property</h2>
      <p className="mb-4">The Services and their contents, features, and functionality (including but not limited to all information, software, text, displays, images, video, and audio, and the design, selection, and arrangement thereof) are owned by WagerProof, its licensors, or other providers of such material and are protected by United States and international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.</p>
      <p className="mb-4">These Terms of Service permit you to use the Services for your personal, non-commercial use only, unless you are otherwise expressly permitted to do so based on your subscription. You must not reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store, or transmit any of the material from the Services, except as follows:</p>
      <ul className="list-disc pl-5 mb-4 space-y-2">
        <li>Your electronic device may temporarily store copies of such materials in RAM incidental to your accessing and viewing those materials.</li>
        <li>You may store files that are automatically cached by your internet browser for display enhancement purposes.</li>
        <li>You may print or download one copy of a reasonable number of pages of the content from the Services for your own personal, non-commercial use and not for further reproduction, publication, or distribution.</li>
        <li>If we provide desktop, mobile, or other applications for download, you may download copies to your electronic devices device solely for your own personal, non-commercial use, provided you agree to be bound by our end user license agreement for such application(s).</li>
      </ul>
      <p className="mb-2">You must not:</p>
      <ul className="list-disc pl-5 mb-4 space-y-2">
        <li>Modify copies of any materials from the Services.</li>
        <li>Delete or alter any copyright, trademark, or other proprietary rights notices from copies of materials from the Services, including any notices related to the Company's machine learning models, algorithms, or AI-generated content.</li>
        <li>Access or use for any commercial purposes any part of the Services or materials available through the Services.</li>
      </ul>
      <p className="mb-4">If you wish to make any use of material from the Services other than that set out in this section, please address your request to: [appropriate email address].</p>
      <p className="mb-4">If you print, copy, modify, download, or otherwise use or provide any other person with access to any part of the Services in breach of these Terms of Service, your right to use the Services will stop immediately and you must, at our option, return or destroy any copies of the materials you have made. No right, title, or interest in or to the Services or any materials made available through the Services are transferred to you, and all rights not expressly granted are reserved by the Company. Any use of the Services not expressly permitted by these Terms of Service is a breach of these Terms of Service and may violate copyright, trademark, and other laws.</p>

      <h2 className="text-2xl font-bold mb-4 text-primary">9. Use of Artificial Intelligence</h2>
      <p className="mb-4">The Services use analytical tools that use artificial intelligence and/or machine learning models (collectively, "AI") designed to provide insights based on available data. You understand and acknowledge the following:</p>
      <ul className="list-disc pl-5 mb-4 space-y-2">
        <li>that the information or materials provided by or through the Services may be machine-generated using AI;</li>
        <li>that AI may generate incomplete, inaccurate, biased, outdated, or misleading information, hallucinations, and/or other errors and therefore should not be taken as infallible or definitive.</li>
        <li>information or materials provided by or through the Services do not constitute financial, gambling, investment, or professional advice of any kind; and</li>
        <li>that you use the Services and the outputs provided by or through the Services solely at your own risk.</li>
      </ul>
      <p className="mb-4">WagerProof makes no representations or warranties of any kind, express or implied, regarding the accuracy, completeness, reliability, timeliness, or usefulness of any information, analysis, prediction, or recommendation provided by or through the Services. You acknowledge and agree that you are solely responsible for verifying all information independently and for any decisions made based on information or materials provided by or through the Services. WagerProof expressly disclaims any liability for any decisions made in reliance on information or other materials provided by or through the Services whether or not generated using AI.</p>

      <h2 className="text-2xl font-bold mb-4 text-primary">10. Limitation of Liability</h2>
      <p className="mb-4"><strong>TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL WAGERPROOF, ITS AFFILIATES, OR ITS OR THEIR MEMBERS, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, SUPPLIERS, OR LICENSORS BE LIABLE FOR DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE, OR INABILITY TO USE, THE SERVICES, ANY PLATFORMS LINKED TO IT, ANY CONTENT ON THE SERVICES OR SUCH OTHER PLATFORMS, INCLUDING ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF DATA, LOSS OF USE, LOSS OF GOODWILL, GAMBLING LOSSES, BETTING LOSSES, FINANCIAL LOSSES FROM RELIANCE ON WAGERBOT OR ANY AI-GENERATED CONTENT, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (I) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICES; (II) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICES; (III) ANY SERVICE OR MATERIAL OBTAINED FROM THE SERVICES; (IV) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT; (V) ANY ERRORS, INACCURACIES, OR OMISSIONS IN WAGERBOT OR AI-GENERATED CONTENT; AND (VI) ANY DECISIONS MADE IN RELIANCE ON INFORMATION PROVIDED THROUGH THE SERVICES; WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR ANY OTHER LEGAL THEORY, WHETHER OR NOT WE HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF FORESEEABLE, AND EVEN IF A REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.</strong></p>
      <p className="mb-4">THE FOREGOING DOES NOT AFFECT ANY LIABILITY THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW. NOTWITHSTANDING THE FOREGOING, IF WAGERPROOF IS FOUND LIABLE TO YOU FOR ANY DAMAGE OR LOSS WHICH ARISES OUT OF OR IS IN ANY WAY CONNECTED WITH YOUR USE OF THE SERVICES, WAGERPROOF'S TOTAL LIABILITY SHALL NOT EXCEED THE GREATER OF (1) THE AMOUNT YOU PAID TO WAGERPROOF IN SUBSCRIPTION FEES IN THE TWELVE (12) MONTHS PRIOR TO THE EVENT GIVING RISE TO LIABILITY, OR (2) ONE THOUSAND DOLLARS ($1,000.00).</p>

      <h2 className="text-2xl font-bold mb-4 text-primary">11. Indemnification</h2>
      <p className="mb-4">You agree to defend, indemnify, and hold harmless WagerProof, its affiliates, and its and their respective members, officers, directors, employees, agents, licensors, suppliers, successors, and assigns from and against any and all claims, liabilities, damages, losses, judgements, awards, fees, penalties, fines, and expenses, including reasonable attorneys' fees and costs, arising out of or in any way connected with (i) your access to or use of the Services, including the use of any materials or information obtained through the Services; (ii) your violation of these Terms of Service; (iii) your infringement of any intellectual property or other right of any person or entity; (iv) any gambling, betting, or wagering activities you engage in based on information from the Services; (v) your violation of any applicable laws or regulations, including gambling laws; or (vi) any third-party claims arising from your use of the Services.</p>

      <h2 className="text-2xl font-bold mb-4 text-primary">12. Governing Law and Jurisdiction</h2>
      <p className="mb-4">All matters relating to the Services and these Terms of Service, and any dispute or claim arising therefrom or related thereto (in each case, including non-contractual disputes or claims), shall be governed and construed in accordance with the laws of Texas, without regard to its conflict of law provisions. Any legal suit, action, or proceeding arising out of, or related to, these Terms of Service or the Services shall be instituted exclusively in the federal courts of the United States or the courts of the State of Texas, in each case located in the City of Austin and County of Travis, although we retain the right to bring any suit, action, or proceeding against you for breach of these Terms of Service in your country of residence or any other relevant country. You waive any and all objections to the exercise of jurisdiction over you by such courts and to venue in such courts.</p>

      <h2 className="text-2xl font-bold mb-4 text-primary">13. Arbitration</h2>
      <p className="mb-4">Any dispute, controversy, or claim arising out of or relating to these Terms of Service or the use of the Services or the information or materials provided on or through the Services, or the breach, termination, enforcement, interpretation, or validity thereof, including the determination of the scope or applicability of this agreement to arbitrate, shall be determined by binding arbitration in Austin, Texas, before one arbitrator. The arbitration shall be administered by the American Arbitration Association in accordance with its Commercial Arbitration Rules, and judgment on the award rendered by the arbitrator may be entered in any court having jurisdiction thereof. The arbitrator shall apply Texas law consistent with the Federal Arbitration Act. Each party shall bear its own costs and expenses in the arbitration. This arbitration provision does not preclude either party from seeking provisional remedies in aid of arbitration from a court of appropriate jurisdiction.</p>

      <h2 className="text-2xl font-bold mb-4 text-primary">14. Limitation on Time to File Claims</h2>
      <p className="mb-4"><strong>ANY CAUSE OF ACTION OR CLAIM YOU MAY HAVE ARISING OUT OF OR RELATING TO THESE TERMS OF SERVICE OR THE SERVICES MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES; OTHERWISE, SUCH CAUSE OF ACTION OR CLAIM IS PERMANENTLY BARRED.</strong></p>

      <h2 className="text-2xl font-bold mb-4 text-primary">15. Waiver and Severability</h2>
      <p className="mb-4">Any waiver by WagerProof of any term or condition set out in these Terms of Service must be in writing and signed by an authorized representative of the Company to be effective. No waiver by the Company shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of the Company to assert a right or provision under these Terms of Service shall not constitute a waiver of such right or provision.</p>
      <p className="mb-4">If any provision of these Terms of Service is held by a court or other tribunal of competent jurisdiction to be invalid, illegal, or unenforceable for any reason, such provision shall be reformed to the minimum extent necessary to make it valid and enforceable while preserving its intent, or if such reformation is not possible, such provision shall be severed from these Terms of Service. The remaining provisions of the Terms of Service will continue in full force and effect. The invalidity or unenforceability of any provision shall not affect the validity or enforceability of any other provision, and any invalid or unenforceable provision shall be deemed replaced by a valid and enforceable provision that most closely approximates the intent and economic effect of the invalid or unenforceable provision.</p>

      <h2 className="text-2xl font-bold mb-4 text-primary">16. Changes to These Terms of Service</h2>
      <p className="mb-4">We reserve the right to modify or replace these Terms of Service at any time at our sole discretion. If a revision is material, we will provide at least thirty (30) days' notice prior to any new terms taking effect. What constitutes a "material" change will be determined at our sole discretion. Changes to these Terms of Service are effective upon the earlier of: (i) your continued use of the Services after notice of such changes, or (ii) thirty (30) days after posting for material changes, or immediately upon posting for non-material changes. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you must stop using the Services. You are expected to check this page from time to time so you are aware of any changes, as they are binding on you.</p>

      <h2 className="text-2xl font-bold mb-4 text-primary">17. Entire Agreement</h2>
      <p className="mb-4">These Terms of Service, including the documents incorporated by reference herein, constitute the sole and entire agreement between you and WagerProof LLC regarding the Services and supersede all prior and contemporaneous understandings, agreements, representations, and warranties, both written and oral, regarding the Services.</p>

      <h2 className="text-2xl font-bold mb-4 text-primary">18. Contact Us</h2>
      <p className="mb-4">Any notices or questions concerning these Terms of Service should be directed to: admin@wagerproof.bet</p>
      </div>
    </>
  );
};

export default TermsAndConditions;
