// GENERATED from the live {sport}_system_rows filter engines (the single WHERE
// shared by the app pages, the systems grader, and now this MCP tool). Regenerate
// with research/systems_deploy/audit_filter_keys.py-style extraction after adding
// filter keys. Pitcher-ID keys (sp/opp_sp) are deliberately excluded.
export const TREND_FILTER_KEYS: Record<string, readonly string[]> = {
  nfl: [
    "above_500", "abs_spread_max", "abs_spread_min", "ats_win_pct_max", "ats_win_pct_min", "ats_win_streak_max",
    "ats_win_streak_min", "avg_cover_margin_max", "avg_cover_margin_min", "coach", "day_of_week", "division",
    "dome", "fav_dog", "h1_abs_spread_max", "h1_abs_spread_min", "h1_ml_max", "h1_ml_min",
    "h1_spread_max", "h1_spread_min", "h1_total_max", "h1_total_min", "h2h_last_ats_win", "h2h_last_fav",
    "h2h_last_home", "h2h_last_over", "h2h_last_win", "h2h_same_season", "h2h_spread_higher", "h2h_spread_lower",
    "last_covered", "last_favorite", "last_margin_max", "last_margin_min", "last_ml", "last_ou",
    "last_over", "last_overtime", "last_spread", "last_won", "loss_streak_max", "loss_streak_min",
    "made_playoffs_prev", "min_games", "ml_max", "ml_min", "more_wins_than_opp_prev", "opp_ats_win_pct_max",
    "opp_ats_win_pct_min", "opp_last_covered", "opp_last_favorite", "opp_last_margin_max", "opp_last_margin_min", "opp_last_over",
    "opp_last_overtime", "opp_last_won", "opp_loss_streak_max", "opp_loss_streak_min", "opp_made_playoffs_prev", "opp_ml_max",
    "opp_ml_min", "opp_over_pct_max", "opp_over_pct_min", "opp_pa_pg_max", "opp_pa_pg_min", "opp_ppg_max",
    "opp_ppg_min", "opp_prev_win_pct_max", "opp_prev_win_pct_min", "opp_tt_max", "opp_tt_min", "opp_win_pct_max",
    "opp_win_pct_min", "opp_win_streak_max", "opp_win_streak_min", "opponent", "over_pct_max", "over_pct_min",
    "over_streak_max", "over_streak_min", "pa_pg_max", "pa_pg_min", "playoff_round", "point_diff_pg_max",
    "point_diff_pg_min", "ppg_max", "ppg_min", "pre_bye", "precip", "prev_win_pct_max",
    "prev_win_pct_min", "prev_wins_max", "prev_wins_min", "primetime", "referee", "rest_max",
    "rest_min", "season_max", "season_min", "season_type", "side", "spread_max",
    "spread_min", "surface", "team", "team_division", "temp_max", "temp_min",
    "total_max", "total_min", "tt_max", "tt_min", "under_streak_max", "under_streak_min",
    "week_max", "week_min", "win_pct_gt_opp", "win_pct_max", "win_pct_min", "win_streak_max",
    "win_streak_min", "wind_max", "wind_min",
  ],
  cfb: [
    "above_500", "abs_spread_max", "abs_spread_min", "ats_win_pct_max", "ats_win_pct_min", "ats_win_streak_max",
    "ats_win_streak_min", "avg_cover_margin_max", "avg_cover_margin_min", "conference", "conference_game", "day_of_week",
    "dome", "fav_dog", "game_type", "h1_abs_spread_max", "h1_abs_spread_min", "h1_ml_max",
    "h1_ml_min", "h1_spread_max", "h1_spread_min", "h1_total_max", "h1_total_min", "h2h_last_ats_win",
    "h2h_last_fav", "h2h_last_home", "h2h_last_over", "h2h_last_win", "h2h_same_season", "h2h_spread_higher",
    "h2h_spread_lower", "last_covered", "last_favorite", "last_margin_max", "last_margin_min", "last_over",
    "last_overtime", "last_won", "loss_streak_max", "loss_streak_min", "made_playoffs_prev", "min_games",
    "ml_max", "ml_min", "more_wins_than_opp_prev", "neutral_site", "opp_ats_win_pct_max", "opp_ats_win_pct_min",
    "opp_last_covered", "opp_last_favorite", "opp_last_margin_max", "opp_last_margin_min", "opp_last_over", "opp_last_overtime",
    "opp_last_won", "opp_loss_streak_max", "opp_loss_streak_min", "opp_made_playoffs_prev", "opp_ml_max", "opp_ml_min",
    "opp_over_pct_max", "opp_over_pct_min", "opp_pa_pg_max", "opp_pa_pg_min", "opp_ppg_max", "opp_ppg_min",
    "opp_prev_win_pct_max", "opp_prev_win_pct_min", "opp_tt_max", "opp_tt_min", "opp_win_pct_max", "opp_win_pct_min",
    "opp_win_streak_max", "opp_win_streak_min", "opponent", "over_pct_max", "over_pct_min", "over_streak_max",
    "over_streak_min", "pa_pg_max", "pa_pg_min", "point_diff_pg_max", "point_diff_pg_min", "ppg_max",
    "ppg_min", "pre_bye", "prev_win_pct_max", "prev_win_pct_min", "prev_wins_max", "prev_wins_min",
    "primetime", "ranked_matchup", "rest_max", "rest_min", "season_max", "season_min",
    "side", "spread_max", "spread_min", "team", "temp_max", "temp_min",
    "total_max", "total_min", "tt_max", "tt_min", "under_streak_max", "under_streak_min",
    "weather", "week_max", "week_min", "win_pct_gt_opp", "win_pct_max", "win_pct_min",
    "win_streak_max", "win_streak_min", "wind_max", "wind_min",
  ],
  mlb: [
    "bp_ip3d_max", "bp_ip3d_min", "bp_xfip_max", "bp_xfip_min", "day_of_week", "division",
    "dome", "doubleheader", "f5_total_max", "f5_total_min", "fav_dog", "h2h_last_ats_win",
    "h2h_last_fav", "h2h_last_home", "h2h_last_margin_max", "h2h_last_margin_min", "h2h_last_over", "h2h_last_win",
    "h2h_same_season", "interleague", "last_covered", "last_favorite", "last_margin_max", "last_margin_min",
    "last_over", "last_result", "loss_streak_max", "loss_streak_min", "min_games", "ml_max",
    "ml_min", "month_max", "month_min", "opp_last_covered", "opp_last_favorite", "opp_last_margin_max",
    "opp_last_margin_min", "opp_last_over", "opp_last_result", "opp_loss_streak_max", "opp_loss_streak_min", "opp_over_pct_max",
    "opp_over_pct_min", "opp_prev_win_pct_max", "opp_prev_win_pct_min", "opp_rapg_max", "opp_rapg_min", "opp_rl_cover_pct_max",
    "opp_rl_cover_pct_min", "opp_rpg_max", "opp_rpg_min", "opp_sp_hand", "opp_sp_xfip_max", "opp_sp_xfip_min",
    "opp_win_pct_max", "opp_win_pct_min", "opp_win_streak_max", "opp_win_streak_min", "opponent", "over_pct_max",
    "over_pct_min", "over_streak_max", "over_streak_min", "pf_runs_max", "pf_runs_min", "prev_win_pct_max",
    "prev_win_pct_min", "prev_wins_max", "prev_wins_min", "rapg_max", "rapg_min", "rest_max",
    "rest_min", "rl_cover_pct_max", "rl_cover_pct_min", "rl_streak_max", "rl_streak_min", "rpg_max",
    "rpg_min", "run_diff_pg_max", "run_diff_pg_min", "season_max", "season_min", "series_game_max",
    "series_game_min", "side", "sp_hand", "sp_xfip_max", "sp_xfip_min", "streak_max",
    "streak_min", "switch_game", "team", "temp_max", "temp_min", "time_max",
    "time_min", "total_max", "total_min", "trip_max", "trip_min", "under_streak_max",
    "under_streak_min", "win_pct_max", "win_pct_min", "win_streak_max", "win_streak_min", "wind_dir",
    "wind_max", "wind_min",
  ],
};
