// User-data tools for the signed-in user's AI agents ("avatars"). These run
// against the Main project through an RLS-scoped client (the user's JWT), so
// isolation is enforced by the database; we ALSO filter by ctx.userId where the
// column exists, as defense in depth.

import {
  readOnly,
  asOptString,
  asOptNumber,
  asSport,
  type SupabaseLikeClient,
  type Tool,
  type ToolContext,
} from "../../types.js";

function requireUser(ctx: ToolContext): string {
  if (!ctx.userId) throw new Error("This tool requires an authenticated user.");
  return ctx.userId;
}

/** Fetch the user's own avatar ids+names (RLS + explicit user filter). */
async function fetchMyAgents(
  main: SupabaseLikeClient,
  userId: string,
): Promise<Array<Record<string, unknown>>> {
  const { data, error } = await main
    .from("avatar_profiles")
    .select("*")
    .eq("user_id", userId)
    .order("created_at", { ascending: false });
  if (error) throw new Error(`avatar_profiles query failed: ${error.message}`);
  return data ?? [];
}

function compactAgent(a: Record<string, unknown>) {
  const p = (a.personality_params as Record<string, unknown>) ?? {};
  return {
    id: a.id,
    name: a.name,
    emoji: a.avatar_emoji,
    color: a.avatar_color,
    archetype: a.archetype,
    preferred_sports: a.preferred_sports,
    is_public: a.is_public,
    is_active: a.is_active,
    auto_generate: a.auto_generate,
    last_generated_at: a.last_generated_at,
    personality: {
      risk_tolerance: p.risk_tolerance,
      underdog_lean: p.underdog_lean,
      over_under_lean: p.over_under_lean,
      preferred_bet_type: p.preferred_bet_type,
      max_picks_per_day: p.max_picks_per_day,
      trust_model: p.trust_model,
    },
    created_at: a.created_at,
  };
}

export const listMyAgents: Tool = {
  name: "list_my_agents",
  title: "List my AI agents",
  scope: "user",
  description:
    "List the signed-in user's own WagerProof AI prediction agents (\"avatars\") — " +
    "their name, archetype, preferred sports, key personality settings, and whether " +
    "each is public and auto-generating picks.",
  annotations: readOnly("List my AI agents"),
  inputSchema: { type: "object", properties: {}, additionalProperties: false },
  async execute(_input, ctx) {
    const userId = requireUser(ctx);
    const agents = await fetchMyAgents(ctx.main, userId);
    return { count: agents.length, agents: agents.map(compactAgent) };
  },
};

export const getAgentPerformance: Tool = {
  name: "get_agent_performance",
  title: "Get agent performance",
  scope: "user",
  description:
    "Get the win-loss-push record, win rate, net units, streaks, and per-sport / " +
    "per-bet-type breakdown for the user's agents. Pass agent_id for one agent, or " +
    "omit it to get every agent the user owns.",
  annotations: readOnly("Get agent performance"),
  inputSchema: {
    type: "object",
    properties: {
      agent_id: { type: "string", description: "Optional avatar id; omit for all the user's agents." },
    },
    additionalProperties: false,
  },
  async execute(input, ctx) {
    const userId = requireUser(ctx);
    const agentId = asOptString(input.agent_id);
    const agents = await fetchMyAgents(ctx.main, userId);
    const owned = agentId ? agents.filter((a) => a.id === agentId) : agents;
    if (owned.length === 0) {
      return { performance: [], message: agentId ? "No such agent owned by you." : "You have no agents." };
    }
    const nameById = new Map(owned.map((a) => [a.id, a.name]));
    const ids = owned.map((a) => a.id);

    const { data: perf, error } = await ctx.main
      .from("avatar_performance_cache")
      .select("*")
      .in("avatar_id", ids);
    if (error) throw new Error(`performance query failed: ${error.message}`);

    const byId = new Map((perf ?? []).map((p) => [p.avatar_id, p]));
    const performance = owned.map((a) => {
      const p = byId.get(a.id) as Record<string, unknown> | undefined;
      return {
        agent_id: a.id,
        name: nameById.get(a.id),
        record: p ? `${p.wins}-${p.losses}-${p.pushes}` : "0-0-0",
        total_picks: p?.total_picks ?? 0,
        pending: p?.pending ?? 0,
        win_rate: p?.win_rate ?? null,
        net_units: p?.net_units ?? 0,
        current_streak: p?.current_streak ?? 0,
        best_streak: p?.best_streak ?? 0,
        worst_streak: p?.worst_streak ?? 0,
        by_sport: p?.stats_by_sport ?? {},
        by_bet_type: p?.stats_by_bet_type ?? {},
        last_calculated_at: p?.last_calculated_at ?? null,
      };
    });
    return { count: performance.length, performance };
  },
};

export const listMyAgentPicks: Tool = {
  name: "list_my_agent_picks",
  title: "List my agent's picks",
  scope: "user",
  description:
    "List picks generated by the user's agents, with each pick's reasoning, " +
    "confidence (a 1-5 analytic score), and graded result. Filter by agent, sport, " +
    "result, or date. Returns the most recent picks first.",
  annotations: readOnly("List my agent's picks"),
  inputSchema: {
    type: "object",
    properties: {
      agent_id: { type: "string", description: "Optional avatar id to filter to one agent." },
      sport: { type: "string", enum: ["nfl", "nba", "cfb", "ncaab", "mlb"], description: "Optional sport filter." },
      result: { type: "string", enum: ["won", "lost", "push", "pending"], description: "Optional graded-result filter." },
      date: { type: "string", description: "Optional game date YYYY-MM-DD." },
      limit: { type: "number", description: "Max picks to return (default 25, max 100)." },
    },
    additionalProperties: false,
  },
  async execute(input, ctx) {
    const userId = requireUser(ctx);
    const agentId = asOptString(input.agent_id);
    const sport = asSport(input.sport);
    const result = asOptString(input.result);
    const date = asOptString(input.date);
    const limit = Math.min(Math.max(asOptNumber(input.limit) ?? 25, 1), 100);

    const agents = await fetchMyAgents(ctx.main, userId);
    const owned = agentId ? agents.filter((a) => a.id === agentId) : agents;
    if (owned.length === 0) return { picks: [], message: "No matching agents." };
    const nameById = new Map(owned.map((a) => [a.id, a.name]));
    const ids = owned.map((a) => a.id);

    let query = ctx.main
      .from("avatar_picks")
      .select("*")
      .in("avatar_id", ids)
      .order("game_date", { ascending: false })
      .limit(limit);
    if (sport) query = query.eq("sport", sport);
    if (result) query = query.eq("result", result);
    if (date) query = query.eq("game_date", date);

    const { data: picks, error } = await query;
    if (error) throw new Error(`avatar_picks query failed: ${error.message}`);

    const formatted = (picks ?? []).map((p) => ({
      id: p.id,
      agent_id: p.avatar_id,
      agent_name: nameById.get(p.avatar_id),
      sport: p.sport,
      matchup: p.matchup,
      game_date: p.game_date,
      bet_type: p.bet_type,
      selection: p.pick_selection,
      odds: p.odds,
      confidence: p.confidence,
      reasoning: p.reasoning_text,
      key_factors: p.key_factors,
      result: p.result,
      actual_result: p.actual_result,
      created_at: p.created_at,
    }));
    return { count: formatted.length, picks: formatted };
  },
};

export const listMyFollows: Tool = {
  name: "list_my_follows",
  title: "List agents I follow",
  scope: "user",
  description:
    "List the public WagerProof agents the user follows, with each followed agent's " +
    "name, archetype, and current win-loss record.",
  annotations: readOnly("List agents I follow"),
  inputSchema: { type: "object", properties: {}, additionalProperties: false },
  async execute(_input, ctx) {
    const userId = requireUser(ctx);
    const { data: follows, error } = await ctx.main
      .from("user_avatar_follows")
      .select("*")
      .eq("user_id", userId)
      .order("followed_at", { ascending: false });
    if (error) throw new Error(`follows query failed: ${error.message}`);
    if (!follows || follows.length === 0) return { count: 0, follows: [] };

    const avatarIds = follows.map((f) => f.avatar_id);
    // Public avatars are readable under RLS even though the user doesn't own them.
    const { data: profiles } = await ctx.main
      .from("avatar_profiles")
      .select("id, name, avatar_emoji, archetype, preferred_sports, is_public")
      .in("id", avatarIds);
    const { data: perf } = await ctx.main
      .from("avatar_performance_cache")
      .select("avatar_id, wins, losses, pushes, win_rate, net_units")
      .in("avatar_id", avatarIds);

    const profById = new Map((profiles ?? []).map((p) => [p.id, p]));
    const perfById = new Map((perf ?? []).map((p) => [p.avatar_id, p]));

    const out = follows.map((f) => {
      const prof = profById.get(f.avatar_id) as Record<string, unknown> | undefined;
      const p = perfById.get(f.avatar_id) as Record<string, unknown> | undefined;
      return {
        agent_id: f.avatar_id,
        name: prof?.name ?? null,
        emoji: prof?.avatar_emoji ?? null,
        archetype: prof?.archetype ?? null,
        preferred_sports: prof?.preferred_sports ?? null,
        record: p ? `${p.wins}-${p.losses}-${p.pushes}` : null,
        win_rate: p?.win_rate ?? null,
        net_units: p?.net_units ?? null,
        notify_on_pick: f.notify_on_pick,
        followed_at: f.followed_at,
      };
    });
    return { count: out.length, follows: out };
  },
};

export const agentTools: Tool[] = [
  listMyAgents,
  getAgentPerformance,
  listMyAgentPicks,
  listMyFollows,
];
