// NFL Team Colors and Utilities
export const getNFLTeamColors = (teamName: string): { primary: string; secondary: string } => {
  const colorMap: { [key: string]: { primary: string; secondary: string } } = {
    'Arizona': { primary: '#97233F', secondary: '#000000' },
    'Atlanta': { primary: '#A71930', secondary: '#000000' },
    'Baltimore': { primary: '#241773', secondary: '#9E7C0C' },
    'Buffalo': { primary: '#00338D', secondary: '#C60C30' },
    'Carolina': { primary: '#0085CA', secondary: '#101820' },
    'Chicago': { primary: '#0B162A', secondary: '#C83803' },
    'Cincinnati': { primary: '#FB4F14', secondary: '#000000' },
    'Cleveland': { primary: '#311D00', secondary: '#FF3C00' },
    'Dallas': { primary: '#003594', secondary: '#869397' },
    'Denver': { primary: '#FB4F14', secondary: '#002244' },
    'Detroit': { primary: '#0076B6', secondary: '#B0B7BC' },
    'Green Bay': { primary: '#203731', secondary: '#FFB612' },
    'Houston': { primary: '#03202F', secondary: '#A71930' },
    'Indianapolis': { primary: '#002C5F', secondary: '#A2AAAD' },
    'Jacksonville': { primary: '#101820', secondary: '#D7A22A' },
    'Kansas City': { primary: '#E31837', secondary: '#FFB81C' },
    'Las Vegas': { primary: '#000000', secondary: '#A5ACAF' },
    'Los Angeles Chargers': { primary: '#0080C6', secondary: '#FFC20E' },
    'Los Angeles Rams': { primary: '#003594', secondary: '#FFA300' },
    'LA Chargers': { primary: '#0080C6', secondary: '#FFC20E' },
    'LA Rams': { primary: '#003594', secondary: '#FFA300' },
    'Miami': { primary: '#008E97', secondary: '#FC4C02' },
    'Minnesota': { primary: '#4F2683', secondary: '#FFC62F' },
    'New England': { primary: '#002244', secondary: '#C60C30' },
    'New Orleans': { primary: '#101820', secondary: '#D3BC8D' },
    'NY Giants': { primary: '#0B2265', secondary: '#A71930' },
    'NY Jets': { primary: '#125740', secondary: '#000000' },
    'Philadelphia': { primary: '#004C54', secondary: '#A5ACAF' },
    'Pittsburgh': { primary: '#FFB612', secondary: '#101820' },
    'San Francisco': { primary: '#AA0000', secondary: '#B3995D' },
    'Seattle': { primary: '#002244', secondary: '#69BE28' },
    'Tampa Bay': { primary: '#D50A0A', secondary: '#FF7900' },
    'Tennessee': { primary: '#0C2340', secondary: '#4B92DB' },
    'Washington': { primary: '#5A1414', secondary: '#FFB612' },
  };
  return colorMap[teamName] || { primary: '#6B7280', secondary: '#9CA3AF' };
};

// CFB Team Colors
export const getCFBTeamColors = (teamName: string): { primary: string; secondary: string } => {
  const colorMap: { [key: string]: { primary: string; secondary: string } } = {
    'Alabama': { primary: '#9E1B32', secondary: '#828A8F' },
    'Auburn': { primary: '#0C2340', secondary: '#E87722' },
    'Georgia': { primary: '#BA0C2F', secondary: '#000000' },
    'Florida': { primary: '#0021A5', secondary: '#FA4616' },
    'LSU': { primary: '#461D7C', secondary: '#FDD023' },
    'Texas A&M': { primary: '#500000', secondary: '#FFFFFF' },
    'Ole Miss': { primary: '#14213D', secondary: '#CE1126' },
    'Mississippi State': { primary: '#5D1725', secondary: '#FFFFFF' },
    'Arkansas': { primary: '#9D2235', secondary: '#FFFFFF' },
    'Kentucky': { primary: '#0033A0', secondary: '#FFFFFF' },
    'Tennessee': { primary: '#FF8200', secondary: '#FFFFFF' },
    'South Carolina': { primary: '#73000A', secondary: '#000000' },
    'Missouri': { primary: '#F1B82D', secondary: '#000000' },
    'Vanderbilt': { primary: '#866D4B', secondary: '#000000' },
    'Ohio State': { primary: '#BB0000', secondary: '#666666' },
    'Michigan': { primary: '#00274C', secondary: '#FFCB05' },
    'Penn State': { primary: '#041E42', secondary: '#FFFFFF' },
    'Michigan State': { primary: '#18453B', secondary: '#FFFFFF' },
    'Wisconsin': { primary: '#C5050C', secondary: '#FFFFFF' },
    'Iowa': { primary: '#FFCD00', secondary: '#000000' },
    'Minnesota': { primary: '#7A0019', secondary: '#FFCC33' },
    'Nebraska': { primary: '#E41C38', secondary: '#FFFFFF' },
    'Illinois': { primary: '#13294B', secondary: '#E84A27' },
    'Northwestern': { primary: '#4E2A84', secondary: '#FFFFFF' },
    'Purdue': { primary: '#CEB888', secondary: '#000000' },
    'Indiana': { primary: '#990000', secondary: '#EEEDEB' },
    'Rutgers': { primary: '#CC0033', secondary: '#000000' },
    'Maryland': { primary: '#E03A3E', secondary: '#FFD520' },
    'Oklahoma': { primary: '#841617', secondary: '#FEFBF2' },
    'Texas': { primary: '#BF5700', secondary: '#FFFFFF' },
    'Oklahoma State': { primary: '#FF7300', secondary: '#000000' },
    'Baylor': { primary: '#003015', secondary: '#FFB81C' },
    'TCU': { primary: '#4D1979', secondary: '#A3A9AC' },
    'Texas Tech': { primary: '#CC0000', secondary: '#000000' },
    'Kansas State': { primary: '#512888', secondary: '#FFFFFF' },
    'Iowa State': { primary: '#C8102E', secondary: '#F1BE48' },
    'Kansas': { primary: '#0051BA', secondary: '#E8000D' },
    'West Virginia': { primary: '#002855', secondary: '#EAAA00' },
    'BYU': { primary: '#002E5D', secondary: '#FFFFFF' },
    'Cincinnati': { primary: '#E00122', secondary: '#000000' },
    'UCF': { primary: '#BA9B37', secondary: '#000000' },
    'Houston': { primary: '#C8102E', secondary: '#FFFFFF' },
    'USC': { primary: '#990000', secondary: '#FFC72C' },
    'UCLA': { primary: '#2D68C4', secondary: '#FFD100' },
    'Oregon': { primary: '#154733', secondary: '#FEE123' },
    'Washington': { primary: '#4B2E83', secondary: '#B7A57A' },
    'Utah': { primary: '#CC0000', secondary: '#FFFFFF' },
    'Arizona State': { primary: '#8C1D40', secondary: '#FFC627' },
    'Arizona': { primary: '#003366', secondary: '#CC0033' },
    'Colorado': { primary: '#000000', secondary: '#CFB87C' },
    'Stanford': { primary: '#8C1515', secondary: '#FFFFFF' },
    'California': { primary: '#003262', secondary: '#FDB515' },
    'Oregon State': { primary: '#DC4405', secondary: '#000000' },
    'Washington State': { primary: '#981E32', secondary: '#5E6A71' },
    'Clemson': { primary: '#F66733', secondary: '#522D80' },
    'Florida State': { primary: '#782F40', secondary: '#CEB888' },
    'Miami': { primary: '#F47321', secondary: '#005030' },
    'North Carolina': { primary: '#7BAFD4', secondary: '#FFFFFF' },
    'NC State': { primary: '#CC0000', secondary: '#FFFFFF' },
    'Virginia Tech': { primary: '#630031', secondary: '#CF4420' },
    'Virginia': { primary: '#232D4B', secondary: '#E57200' },
    'Duke': { primary: '#003087', secondary: '#FFFFFF' },
    'Wake Forest': { primary: '#9E7E38', secondary: '#000000' },
    'Georgia Tech': { primary: '#B3A369', secondary: '#003057' },
    'Boston College': { primary: '#8A1538', secondary: '#CFC493' },
    'Pitt': { primary: '#003594', secondary: '#FFB81C' },
    'Syracuse': { primary: '#F76900', secondary: '#FFFFFF' },
    'Louisville': { primary: '#AD0000', secondary: '#000000' },
    'Notre Dame': { primary: '#0C2340', secondary: '#C99700' },
    'Army': { primary: '#000000', secondary: '#D4AF37' },
    'Navy': { primary: '#002F5F', secondary: '#B3A369' },
    'Air Force': { primary: '#003087', secondary: '#8A8D8F' },
  };
  return colorMap[teamName] || { primary: '#6B7280', secondary: '#9CA3AF' };
};

// NFL Team Initials
export const getNFLTeamInitials = (teamName: string): string => {
  const initialsMap: { [key: string]: string } = {
    'Arizona': 'ARI',
    'Atlanta': 'ATL',
    'Baltimore': 'BAL',
    'Buffalo': 'BUF',
    'Carolina': 'CAR',
    'Chicago': 'CHI',
    'Cincinnati': 'CIN',
    'Cleveland': 'CLE',
    'Dallas': 'DAL',
    'Denver': 'DEN',
    'Detroit': 'DET',
    'Green Bay': 'GB',
    'Houston': 'HOU',
    'Indianapolis': 'IND',
    'Jacksonville': 'JAX',
    'Kansas City': 'KC',
    'Las Vegas': 'LV',
    'Los Angeles Chargers': 'LAC',
    'Los Angeles Rams': 'LAR',
    'LA Chargers': 'LAC',
    'LA Rams': 'LAR',
    'Miami': 'MIA',
    'Minnesota': 'MIN',
    'New England': 'NE',
    'New Orleans': 'NO',
    'NY Giants': 'NYG',
    'NY Jets': 'NYJ',
    'Philadelphia': 'PHI',
    'Pittsburgh': 'PIT',
    'San Francisco': 'SF',
    'Seattle': 'SEA',
    'Tampa Bay': 'TB',
    'Tennessee': 'TEN',
    'Washington': 'WAS',
  };
  return initialsMap[teamName] || teamName.substring(0, 3).toUpperCase();
};

// CFB Team Initials
export const getCFBTeamInitials = (teamName: string): string => {
  const initialsMap: { [key: string]: string } = {
    'Alabama': 'ALA',
    'Auburn': 'AUB',
    'Georgia': 'UGA',
    'Florida': 'UF',
    'LSU': 'LSU',
    'Texas A&M': 'TAMU',
    'Ole Miss': 'MISS',
    'Mississippi State': 'MSST',
    'Arkansas': 'ARK',
    'Kentucky': 'UK',
    'Tennessee': 'TENN',
    'South Carolina': 'SC',
    'Missouri': 'MIZ',
    'Vanderbilt': 'VAN',
    'Ohio State': 'OSU',
    'Michigan': 'MICH',
    'Penn State': 'PSU',
    'Michigan State': 'MSU',
    'Wisconsin': 'WISC',
    'Iowa': 'IOWA',
    'Minnesota': 'MINN',
    'Nebraska': 'NEB',
    'Illinois': 'ILL',
    'Northwestern': 'NW',
    'Purdue': 'PUR',
    'Indiana': 'IND',
    'Rutgers': 'RUT',
    'Maryland': 'MD',
    'Oklahoma': 'OU',
    'Texas': 'TEX',
    'Oklahoma State': 'OKST',
    'Baylor': 'BAY',
    'TCU': 'TCU',
    'Texas Tech': 'TTU',
    'Kansas State': 'KSU',
    'Iowa State': 'ISU',
    'Kansas': 'KU',
    'West Virginia': 'WVU',
    'BYU': 'BYU',
    'Cincinnati': 'CIN',
    'UCF': 'UCF',
    'Houston': 'HOU',
    'USC': 'USC',
    'UCLA': 'UCLA',
    'Oregon': 'ORE',
    'Washington': 'UW',
    'Utah': 'UTAH',
    'Arizona State': 'ASU',
    'Arizona': 'ARIZ',
    'Colorado': 'COLO',
    'Stanford': 'STAN',
    'California': 'CAL',
    'Oregon State': 'ORST',
    'Washington State': 'WSU',
    'Clemson': 'CLEM',
    'Florida State': 'FSU',
    'Miami': 'MIA',
    'North Carolina': 'UNC',
    'NC State': 'NCST',
    'Virginia Tech': 'VT',
    'Virginia': 'UVA',
    'Duke': 'DUKE',
    'Wake Forest': 'WAKE',
    'Georgia Tech': 'GT',
    'Boston College': 'BC',
    'Pitt': 'PITT',
    'Syracuse': 'SYR',
    'Louisville': 'LOU',
    'Notre Dame': 'ND',
    'Army': 'ARMY',
    'Navy': 'NAVY',
    'Air Force': 'AF',
  };
  return initialsMap[teamName] || teamName.substring(0, 3).toUpperCase();
};

// Utility to get contrasting text color for readability
export const getContrastingTextColor = (primaryColor: string, secondaryColor: string): string => {
  const hexToLuminance = (hex: string): number => {
    const rgb = parseInt(hex.slice(1), 16);
    const r = (rgb >> 16) & 0xff;
    const g = (rgb >> 8) & 0xff;
    const b = (rgb >> 0) & 0xff;
    return (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  };

  const primaryLum = hexToLuminance(primaryColor);
  const secondaryLum = hexToLuminance(secondaryColor);
  const avgLuminance = (primaryLum + secondaryLum) / 2;

  return avgLuminance < 0.5 ? '#ffffff' : '#000000';
};

