"""Populate cfb_signal_defs — user-facing plain-English definition for every signal_key in cfb_dryrun_flags.
The app joins cfb_dryrun_flags.signal_key = cfb_signal_defs.signal_key to render a readable card on tap."""
import pandas as pd
import dry_common as C

DEFS = [
 # key, display_name, market, one_liner, definition, why_it_works, bet_direction, typical_hit, conviction
 ("stack", "Model + Sharp-Book Stack", "spread", "Two independent edges agree",
  "Our prediction model and the sharpest sportsbooks point to the same side, while a softer book is still offering a better number on it.",
  "When our fundamentals model and the pro betting market independently agree, the bet is far stronger than either alone.",
  "Bet the agreed side at the best (soft-book) number.", "~72%", "T1"),
 ("soft_book_gap", "Soft-Book Line Gap", "spread", "Beat the slow book",
  "A recreational sportsbook is posting a different spread than the sharp consensus. We take the sharp side at the soft book's better price.",
  "Soft books update slowly and shade toward popular teams, leaving a gap that is essentially free value.",
  "Bet the sharp side at the soft book.", "~57–64%", "T2"),
 ("premium_lay_fav", "Premium Lay-the-Favorite", "spread", "Strong edge on a contained favorite",
  "Our model sees a large, well-supported edge (8+ points) on a Power-5 favorite that isn't a huge number, so we lay the points.",
  "Big model edges on moderate P5 favorites have historically been the model's most reliable favorite plays.",
  "Lay the favorite.", "~63–69%", "T2"),
 ("padded_road_fade", "Padded Road-Team Fade", "spread", "Fade an inflated road rating",
  "A road team's rating is propped up by a weak schedule, and the market is still trusting it. We fade them and take the home side.",
  "Strength-of-schedule-inflated ratings regress, and the market is slow to discount them.",
  "Take the home team.", "~62–64%", "T1"),
 ("g5_fade_after_loss", "Group-of-5 Bounce-Back Fade", "spread", "Fade the overreaction",
  "A top Group-of-5 team just lost and the thin G5 market overcorrects on the rebound game. We fade the public overreaction.",
  "Small Group-of-5 betting markets overshoot after a loss.", "Fade the bouncing-back team.", "~65%", "T1"),
 ("rvr_home", "Ranked-vs-Ranked Home Edge", "spread", "Home edge in marquee games",
  "When both teams are ranked, we side with the home team.",
  "The public gravitates to the ranked road 'name' team, so home-field advantage is underpriced in big games.",
  "Take the home team.", "~57–60%", "T2"),
 ("key_dog", "Key-Number Dog (+2.5/3/3.5)", "spread", "Points around the 3",
  "We take a small underdog getting points near the key number 3.",
  "3 is the most common margin in college football, so small dogs priced around it cover more than the line implies.",
  "Take the underdog + points.", "~54%", "T3"),
 ("key_lay_fav", "Key-Number Favorite (−6.5)", "spread", "Win on the touchdown margin",
  "We lay −6.5 with a favorite, designed to win on the common 7-point (one-touchdown) margin.",
  "7 is a key winning margin; −6.5 cashes on it.", "Lay the favorite at −6.5.", "~57%", "T2"),
 ("conf_sunbelt_fade", "Sun Belt Home-Favorite Fade", "spread", "Fade the home chalk",
  "In the Sun Belt, home favorites are systematically overvalued, so we take the underdog.",
  "Sun Belt home favorites are consistently overbet.", "Take the underdog.", "~58%", "T2"),
 ("conf_bigten_road_fav", "Big Ten Road Favorite", "spread", "Back the road chalk",
  "In Big Ten play, favorites on the road are undervalued, so we back the road favorite.",
  "Road favorites in physical Big Ten games are underpriced.", "Lay the road favorite.", "~55%", "T2"),
 ("model_highedge_dog", "Model High-Edge Underdog", "spread", "Strong dog edge",
  "Our model sees a strong edge on a Power-5 underdog, so we take the dog and the points.",
  "Large model edges on P5 underdogs cover at a solid clip.", "Take the underdog + points.", "~58–60%", "T2"),
 ("model_road_value", "Model Road Value", "spread", "Public fades the road team",
  "Our model has a moderate edge on a Power-5 road team that the public is fading.",
  "Public home bias leaves value on solid road teams.", "Take the road team.", "~52–54%", "T3"),
 ("fade_home_backup_qb", "Backup-QB Fade (Home)", "spread", "Bet against the backup",
  "The home team is starting a backup quarterback, so we bet the away side.",
  "Markets are slow to fully discount a backup QB.", "Take the away team.", "~60%", "T3"),
 ("g5_dog_wk1_bigfav", "Week-1 G5 Dog vs Big P5 Favorite", "spread", "Take the G5 getting a big Week-1 number",
  "In a season opener, a Power-5 team is laying between 21 and 27.5 points to a Group-of-5 opponent. We take the Group-of-5 underdog and the points.",
  "Power-5 teams build a big Week-1 lead and then empty the bench, and the Group-of-5 dog reliably backdoors a three-plus-score number. The underdog has covered ~76% in this exact spot — 8 of the last 9 openers — on a small sample (~41 games).",
  "Take the Group-of-5 underdog + points.", "~76% ATS (small sample, ~41 games)", "T3"),
 ("conf_aac_over", "American Conference Over", "total", "Up-tempo points",
  "Up-tempo American Athletic Conference games in this total range go over more often.",
  "AAC pace produces more points than the posted total expects.", "Bet the over.", "~57%", "T2"),
 ("conf_sunbelt_under", "Sun Belt Under", "total", "Ground-and-pound",
  "Run-heavy Sun Belt games in this total range tend to stay under.",
  "Ground-based Sun Belt offenses shorten games and limit scoring.", "Bet the under.", "~68% (small sample)", "T2"),
 ("form_over_hot_under", "Hot-Over Regression (Under)", "total", "Scoring cools off",
  "Both teams have been going over a lot lately and the total is modest, so we take the under as scoring regresses.",
  "Over-streaks mean-revert — this is our most reliable totals signal.", "Bet the under.", "~58%", "T2"),
 ("fade_high_total", "Inflated High Total (Under)", "total", "Fade a bloated number",
  "The posted total is very high (60+), so we take the under.",
  "Books shade high totals upward to attract public over-betting.", "Bet the under.", "~55%", "T3"),
 ("fade_low_total", "Low Total (Over)", "total", "Mild low-total bounce",
  "The posted total is very low (≤50), so we lean over.",
  "Mild mean-reversion on suppressed totals — near break-even, so this is tracked at small stakes.",
  "Bet the over.", "~52% (track-only)", "track"),
 ("model_total_over", "Model Over Edge", "total", "Model projects more points",
  "Our totals model projects materially more points than the posted total.",
  "The unanchored model catches underpriced scoring environments.", "Bet the over.", "~55%", "T3"),
 ("model_total_over_pace", "Model Over — Pace", "total", "Underpriced tempo",
  "A low-total Power-5 game with fast pace that our model expects to outscore the number.",
  "Pace is underweighted in low totals.", "Bet the over.", "~56%", "T2"),
 ("model_total_under", "Model Under Edge", "total", "Model projects fewer points",
  "Our model projects fewer points, supported by a high total and/or a weak-passing-defense matchup.",
  "Model and game structure agree on the under.", "Bet the under.", "~58%", "T2"),
 ("opener_under", "Week 1 Opener Under", "total", "Slow starts",
  "Season openers tend to play under as offenses start slow.", "Rust and conservative early-season game scripts.",
  "Bet the under.", "~55%", "T3"),
 ("ranked_upset_letdown_under", "Post-Upset Letdown Under", "total", "Emotional hangover",
  "A team coming off a ranked upset is in a lower-scoring letdown spot.", "Emotional letdown after a signature win.",
  "Bet the under.", "~56%", "T3"),
 ("primetime_rivalry_letdown_under", "Primetime Rivalry Letdown Under", "total", "Post-rivalry dip",
  "A letdown spot following a primetime rivalry game; scoring dips.", "Energy/emotion hangover after a marquee night game.",
  "Bet the under.", "~56%", "T3"),
 ("backup_qb_under", "Backup-QB Under", "total", "Backup offense scores less",
  "A backup quarterback is starting and the game projects under.", "Backup offenses score less than the posted total assumes.",
  "Bet the under.", "~60%", "T3"),
 ("rivalry_week_over", "Rivalry-Week Over", "total", "Late-season points",
  "Late-season rivalry / championship-week games lean over.", "Emotional, high-variance late-season spots trend over.",
  "Bet the over.", "~52% (track-only)", "track"),
 ("team_total", "Team Total (model)", "team_total", "Projected points vs the posted team total",
  "We project how many points this team will score, then compare it to the sportsbook's posted team total. If our projection is meaningfully BELOW the line we lean UNDER; if it's ABOVE (Power-5 teams) we lean OVER. Example: the model projects Sam Houston for 19.7 points vs a posted 23.5, so we lean UNDER. (This sides WITH our projection — it is not a fade.)",
  "Posted team totals are derived from the game total and spread and get far less attention than the main markets, so they're softer — our full-game model catches teams the number misprices.",
  "UNDER when our projection is below the line; OVER when above (overs are Power-5 only). Take the best number across books.",
  "~57% under / ~62% over (P5)", "T2"),
 ("g5_tt_under_wk1", "Week-1 G5 Team-Total Under", "team_total", "Fade the G5 offense in the opener",
  "In a competitive Week-1 game (spread under 21) between a Group-of-5 team and a Power-5 opponent, we take the UNDER on the Group-of-5 team's team total.",
  "Group-of-5 offenses start slow against Power-5 defenses in the opener and get held below their already-low team total. The G5 has stayed under ~73% of the time and leaned under in all three seasons we have team-total data for (2023-2025, ~37 games).",
  "Bet the Group-of-5 team's team-total UNDER.", "~73% under (small sample, 2023+ only)", "T3"),
 ("style_offense_under", "Style-Underperformance Under", "total", "Offense keeps struggling vs a defense type",
  "This team's offense has scored below its own season efficiency baseline against this opponent's STYLE of defense across its last two-plus games versus that style, so we take the UNDER — on the game total and on the team's own team total.",
  "A team that repeatedly underperforms its own level against a defensive archetype tends to keep doing it, and the total gets shaded only slightly for it. It's a private, efficiency-based read (not a public record) that the softer CFB market underprices; the more it has underperformed, the stronger the lean.",
  "Bet the UNDER (game total + that team's team total).", "~54% game / ~56-61% team total (dose-responsive)", "T3"),
 ("h1_spread", "1st-Half Spread (model)", "h1_spread", "Half-game model edge",
  "Our 1st-half model — built only on tempo, style, and situational factors (it deliberately ignores raw team strength, which the half-spread already prices) — disagrees with the posted 1st-half spread.",
  "The edge lives in what the 'half the full spread' formula throws away.", "Bet the model's side.", "~54%", "T3"),
 ("h1_total", "1st-Half Total (tempo model)", "h1_total", "Half-game pace edge",
  "Our 1st-half total model, driven by pace and possessions, disagrees with the posted 1st-half total. Bet at the best number.",
  "1st-half totals underprice tempo.", "Bet the model's side at the best book.", "~55–56%", "T3"),
 ("h1_ml", "1st-Half Moneyline (dog conversion)", "h1_ml", "Underdog to lead at the half",
  "When our 1st-half model projects an underdog to actually be ahead at halftime, we take that dog's 1st-half moneyline for a bigger payout. Small stakes / tracking.",
  "Outright-win edges pay far more on the moneyline than the spread; small sample so far.", "Take the underdog's 1H moneyline.", "+24% ROI (small sample)", "track"),
 ("model_lean", "Model Lean", "spread", "Model number only",
  "Our model's predicted number differs from the line, but no high-confidence spot signal is attached. Lowest-conviction.",
  "The standalone model is a +CLV product, not a strong stand-alone bet — shown for reference.", "Model side, small stake.", "~50–53%", "track"),
]
df = pd.DataFrame(DEFS, columns=["signal_key", "display_name", "market", "one_liner", "definition",
                                 "why_it_works", "bet_direction", "typical_hit", "default_conviction"])
print(f"cfb_signal_defs rows: {len(df)}")
C.wipe("cfb_signal_defs", "signal_key=not.is.null")
C.insert("cfb_signal_defs", df)
