"""Populate cfb_signal_defs — user-facing plain-English definition for every signal_key in cfb_dryrun_flags.
The app joins cfb_dryrun_flags.signal_key = cfb_signal_defs.signal_key to render a readable card on tap."""
import pandas as pd
import dry_common as C

DEFS = [
 # key, display_name, market, one_liner, definition, why_it_works, bet_direction, typical_hit, conviction
 ("stack", "Model + Sharp-Book Stack", "spread", "Two independent edges agree",
  "Our prediction model and the sharpest sportsbooks point to the same side, while a softer book is still offering a better number on it.",
  "When our fundamentals model and the pro betting market independently agree, the bet is far stronger than either alone.",
  "Bet the agreed side at the best (soft-book) number.", "~72%", "T1"),
 ("soft_book_gap", "Soft-Book Line Gap", "spread", "Beat the slow book",
  "A recreational sportsbook is posting a different spread than the sharp consensus. We take the sharp side at the soft book's better price.",
  "Soft books update slowly and shade toward popular teams, leaving a gap that is essentially free value.",
  "Bet the sharp side at the soft book.", "~57–64%", "T2"),
 ("premium_lay_fav", "Premium Lay-the-Favorite", "spread", "Strong edge on a contained favorite",
  "Our model sees a large, well-supported edge (8+ points) on a Power-5 favorite that isn't a huge number, so we lay the points.",
  "Big model edges on moderate P5 favorites have historically been the model's most reliable favorite plays.",
  "Lay the favorite.", "~63–69%", "T2"),
 ("padded_road_fade", "Padded Road-Team Fade", "spread", "Fade an inflated road rating",
  "A road team's rating is propped up by a weak schedule, and the market is still trusting it. We fade them and take the home side.",
  "Strength-of-schedule-inflated ratings regress, and the market is slow to discount them.",
  "Take the home team.", "~62–64%", "T1"),
 ("g5_fade_after_loss", "Group-of-5 Bounce-Back Fade", "spread", "Fade the overreaction",
  "A top Group-of-5 team just lost and the thin G5 market overcorrects on the rebound game. We fade the public overreaction.",
  "Small Group-of-5 betting markets overshoot after a loss.", "Fade the bouncing-back team.", "~65%", "T1"),
 ("rvr_home", "Ranked-vs-Ranked Home Edge", "spread", "Home edge in marquee games",
  "When both teams are ranked, we side with the home team.",
  "The public gravitates to the ranked road 'name' team, so home-field advantage is underpriced in big games.",
  "Take the home team.", "~57–60%", "T2"),
 ("key_dog", "Key-Number Dog (+2.5/3/3.5)", "spread", "Points around the 3",
  "We take a small underdog getting points near the key number 3.",
  "3 is the most common margin in college football, so small dogs priced around it cover more than the line implies.",
  "Take the underdog + points.", "~54%", "T3"),
 ("key_lay_fav", "Key-Number Favorite (−6.5 to −7.5)", "spread", "Win on the touchdown margin",
  "We lay a touchdown-sized favorite priced at −6.5, −7, or −7.5 on DraftKings, designed to win on the common 7-point (one-touchdown) margin.",
  "7 is the most common winning margin in college football and the public habitually takes the points with the dog, so touchdown favorites cover more than the line implies. A DraftKings-specific band study has them covering ~55% across −6.5 to −7.5 (4 of the last 5 seasons; ~58% at exactly −7/−7.5).",
  "Lay the favorite at −6.5 to −7.5.", "~55% (−7/−7.5 ~58%), 4/5 seasons", "T2"),
 ("conf_sunbelt_fade", "Sun Belt Home-Favorite Fade", "spread", "Fade the home chalk",
  "In the Sun Belt, home favorites are systematically overvalued, so we take the underdog.",
  "Sun Belt home favorites are consistently overbet.", "Take the underdog.", "~58%", "T2"),
 ("conf_bigten_road_fav", "Big Ten Road Favorite", "spread", "Back the road chalk",
  "In Big Ten play, favorites on the road are undervalued, so we back the road favorite.",
  "Road favorites in physical Big Ten games are underpriced.", "Lay the road favorite.", "~55%", "T2"),
 ("model_highedge_dog", "Model High-Edge Underdog", "spread", "Strong dog edge",
  "Our model sees a strong edge on a Power-5 underdog, so we take the dog and the points.",
  "Large model edges on P5 underdogs cover at a solid clip.", "Take the underdog + points.", "~58–60%", "T2"),
 ("model_road_value", "Model Road Value", "spread", "Public fades the road team",
  "Our model has a moderate edge on a Power-5 road team that the public is fading.",
  "Public home bias leaves value on solid road teams.", "Take the road team.", "~52–54%", "T3"),
 ("fade_home_backup_qb", "Backup-QB Fade (Home)", "spread", "Bet against the backup",
  "The home team is starting a backup quarterback, so we bet the away side.",
  "Markets are slow to fully discount a backup QB.", "Take the away team.", "~60%", "T3"),
 ("g5_dog_wk1_bigfav", "Week-1 G5 Dog vs Big P5 Favorite", "spread", "Take the G5 getting a big Week-1 number",
  "In a season opener, a Power-5 team is laying between 21 and 27.5 points to a Group-of-5 opponent. We take the Group-of-5 underdog and the points.",
  "Power-5 teams build a big Week-1 lead and then empty the bench, and the Group-of-5 dog reliably backdoors a three-plus-score number. The underdog has covered ~76% in this exact spot — 8 of the last 9 openers — on a small sample (~41 games).",
  "Take the Group-of-5 underdog + points.", "~76% ATS (small sample, ~41 games)", "T3"),
 ("ret_prod_edge", "Week 1-3 Returning-Production Edge", "spread", "Back the more-experienced roster early",
  "In weeks 1-3, we back the team that returns much more of last year's production than its opponent (a preseason returning-production differential of 20+ points).",
  "Early-season lines lean on last year's ratings, talent, and recruiting and UNDER-weight roster continuity, so the more-experienced team is systematically undervalued before the market has current-season data. Survives a talent control (continuity works even when the team is the LESS-talented side) and the edge decays by week 4 once the market catches up.",
  "Back the more-experienced team on the spread.", "~54% ATS, 9 of 9 seasons (+3.9%)", "T2"),
 ("portal_talent_influx", "Week 1-3 Portal Talent Influx", "spread", "Back a big blue-chip portal haul early",
  "In weeks 1-3, we back a team that added three or more four-star-plus transfer-portal players (and more than its opponent did).",
  "A big influx of blue-chip portal talent isn't fully baked into early lines, which anchor on last year's roster + recruiting. The effect is strongest when a modestly-recruited team loads up via the portal, and it decays by week 4. Sibling of the returning-production edge (that one keeps its guys; this one adds new ones).",
  "Back the portal-loaded team on the spread.", "~57% ATS wk1-3 (2021-25, small sample — track-plus)", "T3"),
 ("conf_aac_over", "American Conference Over", "total", "Up-tempo points",
  "Up-tempo American Athletic Conference games in this total range go over more often.",
  "AAC pace produces more points than the posted total expects.", "Bet the over.", "~57%", "T2"),
 ("conf_sunbelt_under", "Sun Belt Under", "total", "Ground-and-pound",
  "Run-heavy Sun Belt games in this total range tend to stay under.",
  "Ground-based Sun Belt offenses shorten games and limit scoring.", "Bet the under.", "~68% (small sample)", "T2"),
 ("form_over_hot_under", "Hot-Over Regression (Under)", "total", "Scoring cools off",
  "Both teams have been going over a lot lately and the total is modest, so we take the under as scoring regresses.",
  "Over-streaks mean-revert — this is our most reliable totals signal.", "Bet the under.", "~58%", "T2"),
 ("regime_fade_hc", "Regime Fade: New Coach Overrated", "spread", "Fade the rating, trust the market",
  "Preseason power ratings still lean on a team with a first-year head coach, disagreeing with the betting line by 2+ points — we bet against that team, with the market's adjustment.",
  "Betting markets price coaching transitions better than rating systems do. On true preseason ratings 2018-25 this fade hit 58% (+11.5% ROI, n=137) with five straight positive seasons 2021-25; fading the mirror-image side loses 38%, confirming the direction. Weeks 1-3 only; TRACKING tier until a live season confirms.",
  "Bet against the new-coach team the ratings like.", "~58% backtest, tracking", "track"),
 ("regime_fade_teardown", "Regime Fade: Roster Teardown", "spread", "Ratings can't see a gutted roster",
  "Preseason ratings lean on a team returning under 30% of last year's production (same coach), disagreeing with the line by 2+ — we bet against that team.",
  "The coach-free variant of the regime fade: rating systems anchor to last year's team; the market prices the exodus. 56% across 2018-25, positive 5 of 6 seasons. The combined new-HC + teardown core hit 61% with 6 straight positive seasons. Weeks 1-3 only; TRACKING tier.",
  "Bet against the gutted-roster team the ratings like.", "~56% backtest, tracking", "track"),
 ("regime_follow_hc", "Regime Follow: Ride vs New Coach", "spread", "Ratings right when the opponent rebuilds",
  "Preseason ratings favor a stable team against a first-year-head-coach opponent, beyond what the line says — we ride the ratings side.",
  "The mirror of the regime fade: when the regime uncertainty is all on the other side, the ratings' lean is trustworthy (62% backtest, n=111). Weeks 1-3 only; TRACKING tier until a live season confirms.",
  "Bet the ratings' side vs the new-coach opponent.", "~62% backtest, tracking", "track"),
 ("fade_high_total", "Inflated High Total (Under)", "total", "Fade a bloated number",
  "The posted total is very high (60+), so we take the under.",
  "Books shade high totals upward to attract public over-betting — the totals version of the favorite-longshot bias. A DraftKings-specific band study confirms it: totals of 60+ go under ~57% (4 of 5 seasons, +8% ROI), and the whole 56+ range leans under.",
  "Bet the under.", "~57% (60+), 4/5 seasons", "T3"),
 ("fade_low_total", "Low Total (Over)", "total", "Mild low-total bounce",
  "The posted total is very low (≤50), so we lean over.",
  "Mild mean-reversion on suppressed totals — near break-even, so this is tracked at small stakes.",
  "Bet the over.", "~52% (track-only)", "track"),
 ("model_total_over", "Model Over Edge", "total", "Model projects more points",
  "Our totals model projects materially more points than the posted total.",
  "The unanchored model catches underpriced scoring environments.", "Bet the over.", "~55%", "T3"),
 ("model_total_over_pace", "Model Over — Pace", "total", "Underpriced tempo",
  "A low-total Power-5 game with fast pace that our model expects to outscore the number.",
  "Pace is underweighted in low totals.", "Bet the over.", "~56%", "T2"),
 ("model_total_under", "Model Under Edge", "total", "Model projects fewer points",
  "Our model projects fewer points, supported by a high total and/or a weak-passing-defense matchup.",
  "Model and game structure agree on the under.", "Bet the under.", "~58%", "T2"),
 ("opener_under", "Week 1 Opener Under", "total", "Slow starts",
  "Season openers tend to play under as offenses start slow.", "Rust and conservative early-season game scripts.",
  "Bet the under.", "~55%", "T3"),
 ("ranked_upset_letdown_under", "Post-Upset Letdown Under", "total", "Emotional hangover",
  "A team coming off a ranked upset is in a lower-scoring letdown spot.", "Emotional letdown after a signature win.",
  "Bet the under.", "~56%", "T3"),
 ("primetime_rivalry_letdown_under", "Primetime Rivalry Letdown Under", "total", "Post-rivalry dip",
  "A letdown spot following a primetime rivalry game; scoring dips.", "Energy/emotion hangover after a marquee night game.",
  "Bet the under.", "~56%", "T3"),
 ("backup_qb_under", "Backup-QB Under", "total", "Backup offense scores less",
  "A backup quarterback is starting and the game projects under.", "Backup offenses score less than the posted total assumes.",
  "Bet the under.", "~60%", "T3"),
 ("rivalry_week_over", "Rivalry-Week Over", "total", "Late-season points",
  "Late-season rivalry / championship-week games lean over.", "Emotional, high-variance late-season spots trend over.",
  "Bet the over.", "~52% (track-only)", "track"),
 ("team_total", "Team Total (model)", "team_total", "Projected points vs the posted team total",
  "We project how many points this team will score, then compare it to the sportsbook's posted team total. If our projection is meaningfully BELOW the line we lean UNDER; if it's ABOVE (Power-5 teams) we lean OVER. Example: the model projects Sam Houston for 19.7 points vs a posted 23.5, so we lean UNDER. (This sides WITH our projection — it is not a fade.)",
  "Posted team totals are derived from the game total and spread and get far less attention than the main markets, so they're softer — our full-game model catches teams the number misprices.",
  "UNDER when our projection is below the line; OVER when above (overs are Power-5 only). Take the best number across books.",
  "~57% under / ~62% over (P5)", "T2"),
 ("g5_tt_under_wk1", "Week-1 G5 Team-Total Under", "team_total", "Fade the G5 offense in the opener",
  "In a competitive Week-1 game (spread under 21) between a Group-of-5 team and a Power-5 opponent, we take the UNDER on the Group-of-5 team's team total.",
  "Group-of-5 offenses start slow against Power-5 defenses in the opener and get held below their already-low team total. The G5 has stayed under ~73% of the time and leaned under in all three seasons we have team-total data for (2023-2025, ~37 games).",
  "Bet the Group-of-5 team's team-total UNDER.", "~73% under (small sample, 2023+ only)", "T3"),
 ("style_offense_under", "Style-Underperformance Under", "total", "Offense keeps struggling vs a defense type",
  "This team's offense has scored below its own season efficiency baseline against this opponent's STYLE of defense across its last two-plus games versus that style, so we take the UNDER — on the game total and on the team's own team total.",
  "A team that repeatedly underperforms its own level against a defensive archetype tends to keep doing it, and the total gets shaded only slightly for it. It's a private, efficiency-based read (not a public record) that the softer CFB market underprices; the more it has underperformed, the stronger the lean.",
  "Bet the UNDER (game total + that team's team total).", "~54% game / ~56-61% team total (dose-responsive)", "T3"),
 ("h1_spread", "1st-Half Spread (model)", "h1_spread", "Half-game model edge",
  "Our 1st-half model — built only on tempo, style, and situational factors (it deliberately ignores raw team strength, which the half-spread already prices) — disagrees with the posted 1st-half spread.",
  "The edge lives in what the 'half the full spread' formula throws away.", "Bet the model's side.", "~54%", "T3"),
 ("h1_total", "1st-Half Total (tempo model)", "h1_total", "Half-game pace edge",
  "Our 1st-half total model, driven by pace and possessions, disagrees with the posted 1st-half total. Bet at the best number.",
  "1st-half totals underprice tempo.", "Bet the model's side at the best book.", "~55–56%", "T3"),
 ("h1_ml", "1st-Half Moneyline (dog conversion)", "h1_ml", "Underdog to lead at the half",
  "When our 1st-half model projects an underdog to actually be ahead at halftime, we take that dog's 1st-half moneyline for a bigger payout. Small stakes / tracking.",
  "Outright-win edges pay far more on the moneyline than the spread; small sample so far.", "Take the underdog's 1H moneyline.", "+24% ROI (small sample)", "track"),
 ("home_dog_ml", "Small Home-Dog Moneyline", "ml", "Home underdog outright value",
  "DraftKings prices the HOME team as a small underdog (+100 to +140 on the moneyline), so we take the home team to win outright at that price.",
  "Road favorites are systematically overbet in college football, so home underdogs are underpriced to win outright. In a DraftKings-specific study, home dogs in the +100..+140 band won ~48% against a ~43% implied probability — a +5.9% flat-bet ROI across 4 of the last 5 seasons. The edge is HOME-only (away dogs in the same band don't hold) and fades on bigger prices, so it's confined to the small-dog band.",
  "Take the home team's moneyline.", "~48% win / +5.9% ROI, 4/5 seasons", "T3"),
 ("roster_hype_fade", "Week 1 Roster-Hype Fade", "spread", "Fade the loaded roster in the opener",
  "In Week 1, we bet against the team that returns much more of last year's production than its opponent — the market now overpays for a 'loaded' returning roster.",
  "The market learned returning-production and portal data: in 2022 the loaded-roster side covered 57-61% of openers, but by 2024-25 that flipped to 37-43% as books began overpricing continuity. Fading the hyped roster hit ~61% against the opener across the last two seasons, positive both years. Portal-era only, two seasons of evidence — tracked at paper stakes until a live season confirms.",
  "Bet against the team returning more of last year's production.", "~61% vs open wk1 (2024-25, n=83 — tracking)", "track"),
 ("coach_pace_under", "Weeks 1-3 New Fast-Coach Under", "total", "New up-tempo coach, market too high",
  "A new head coach whose previous offense played much faster than this team's takes over, and the market posts a high total expecting instant tempo — we bet the game total under in weeks 1-3.",
  "Betting markets over-hype a new fast scheme before it's installed: new personnel run the coach's tempo without his old efficiency, and those games land well short of their inflated totals (the study's motivating cell beat the closing total by ~5 points). At a pace gap of +4 possessions-worth or more, the under hit ~67% in weeks 1-3. Small sample — tracked at paper stakes.",
  "Bet the game total under.", "~67% under wk1-3 (pace gap >=+4, n=21 — tracking)", "track"),
 ("core_total_edge", "In-Season Ratings vs the Total", "total",
  "Our in-season scoring ratings disagree with the posted total",
  "From week 5 on, each team's offense and defense get rated on what they've actually done this season, adjusted for who they played. When those ratings say a game should score at least 4 points more (or fewer) than the posted total, we bet that side — and the bet gets stronger when the line has already started moving our way.",
  "Once real games pile up, these ratings catch a scoring environment faster than totals get updated. On its own this hit 54.1% across five straight seasons. The real weapon is agreement with the market: when the line has already moved at least 1.5 points toward our side, the win rate jumps to about 66% on the latest five-season re-test, profitable every season. Timing matters too: a move arriving in the final hours before kickoff is the strongest confirmation (60% on its own), while a line that moved early in the week and then went quiet is a warning sign — our tier updates hourly on game day to reflect exactly that. One discipline: if the line has ALREADY moved 2.5+ points, the value is gone and we never chase it.",
  "Bet the over/under our ratings point to.", "54.1% base 5/5 seasons; +steam >=1.5: ~61% (+16%)", "track"),
 ("tt_away_under", "Road Team Under", "team_total",
  "The total looks inflated, and the road team's number is where the extra points hide",
  "When our in-season ratings say a game's total is at least 4 points too high, we don't just bet the game under — we also bet the ROAD team's individual total UNDER. Bettors love overs and love home teams, so books pad home team totals to absorb that action, which quietly parks most of the inflated points on the road team's number instead.",
  "Across the last three seasons this hit 61.3% of 271 bets (61%, 60%, 62% year by year — remarkably steady), returning about +17% per bet at standard juice. It even beats betting the game under in the same spots (56.8%). The identical bet on the HOME team's total wins nothing (48.7%), which is exactly what you'd expect if books shade the home number — that asymmetry is the whole edge.",
  "Bet the road team's team total UNDER.", "61.3% (n=271, 3/3 seasons 60-62%), +16.9% @ -110", "T2"),
 ("early_total_edge", "Weeks 1-3 Early Total Edge", "total",
  "Our preseason projections disagree with the posted total",
  "In the first three weeks, our preseason model — built from each team's returning players, recruiting, and last season's offense/defense adjusted for schedule — says a game should score at least 4 points more (or fewer) than the posted total. We bet the side the model points to.",
  "Early-season totals lean on last year's scoring, and our projections re-price the new season faster than the market does. At 4+ points of disagreement this hit 55.1% across 352 bets, profitable in all five seasons tested; at 6+ points it hit 57.9%. It's the early-season version of our in-season ratings edge. (The same model's SPREAD disagreements showed no edge, so we never bet those.)",
  "Bet the over/under the model total points to.", "55.1% (n=352, 5/5 seasons); >=6 pts: 57.9%", "T3"),
 ("model_lean", "Model Lean", "spread",
  "Model number only",
  "Our model's predicted number differs from the line, but no validated betting signal is attached. This is the lowest-confidence tier — shown for information, not as a play.",
  "The model's number is a good long-term reference (it consistently lands closer to final results than a coin flip), but a raw disagreement with the line, on its own, is not a proven bet.",
  "Model side, small stake.", "~50-53%", "track"),
]
df = pd.DataFrame(DEFS, columns=["signal_key", "display_name", "market", "one_liner", "definition",
                                 "why_it_works", "bet_direction", "typical_hit", "default_conviction"])
print(f"cfb_signal_defs rows: {len(df)}")
C.wipe("cfb_signal_defs", "signal_key=not.is.null")
C.insert("cfb_signal_defs", df)
