package com.wagerproof.core.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Maps an agent to one of the 8 pixel-office sprite sheets (`avatar_0`…`avatar_7`)
 * via a stable hash of the agent's id, so an agent always shows the same
 * character everywhere regardless of roster order.
 */
object AgentSpriteIndex {
    /**
     * Deterministic 0…7 character index from any stable seed. FNV-1a 64-bit over
     * UTF-8 bytes — must match iOS byte-for-byte, so never use hashCode().
     */
    fun forSeed(seed: String): Int {
        var h = 0xcbf29ce484222325uL
        for (b in seed.encodeToByteArray()) {
            // toUByte first: a signed Byte would sign-extend and corrupt the hash.
            h = (h xor b.toUByte().toULong()) * 0x100000001b3uL
        }
        return (h % 8uL).toInt()
    }
}

/**
 * Mirror of an `avatar_profiles` row in main Supabase (RN `AgentProfile`, iOS
 * `Agent`). Tolerant decode: list queries use a slim column projection (no
 * JSONB columns) and must still decode — only id/userId/name/createdAt are
 * required, everything else defaults.
 */
@Serializable
data class Agent(
    val id: String,
    @SerialName("user_id") val userId: String,
    var name: String,
    @SerialName("avatar_emoji") var avatarEmoji: String = "🤖",
    @SerialName("avatar_color") var avatarColor: String = "#6366f1",
    /** Owner-picked pixel-office character (0…7). Null = legacy hash-of-id character. */
    @SerialName("sprite_index") var spriteIndexOverride: Int? = null,
    @SerialName("preferred_sports") var preferredSports: List<AgentSport> = emptyList(),
    @Serializable(with = AgentArchetypeSerializer::class)
    var archetype: AgentArchetype? = null,
    @SerialName("personality_params") var personalityParams: AgentPersonalityParams = AgentPersonalityParams.default,
    @SerialName("custom_insights") var customInsights: AgentCustomInsights = AgentCustomInsights.empty,
    @SerialName("is_public") var isPublic: Boolean = false,
    @SerialName("is_active") var isActive: Boolean = true,
    @SerialName("created_at") val createdAt: String,
    // Swift falls back to createdAt when updated_at is absent — expose that via
    // a computed property over the raw wire value.
    @SerialName("updated_at") private val updatedAtRaw: String? = null,
    @SerialName("auto_generate") var autoGenerate: Boolean = true,
    @SerialName("auto_generate_time") var autoGenerateTime: String = "09:00",
    @SerialName("auto_generate_timezone") var autoGenerateTimezone: String = "America/New_York",
    @SerialName("is_widget_favorite") var isWidgetFavorite: Boolean = false,
    @SerialName("last_generated_at") var lastGeneratedAt: String? = null,
    @SerialName("last_auto_generated_at") var lastAutoGeneratedAt: String? = null,
    @SerialName("owner_last_active_at") var ownerLastActiveAt: String? = null,
    @SerialName("daily_generation_count") var dailyGenerationCount: Int = 0,
    @SerialName("last_generation_date") var lastGenerationDate: String? = null,
) {
    val updatedAt: String get() = updatedAtRaw ?: createdAt

    /**
     * Pixel-office character index (0…7) — the owner's pick (`sprite_index`)
     * when valid, else the legacy stable hash of the id.
     */
    val spriteIndex: Int
        get() {
            val idx = spriteIndexOverride
            if (idx != null && idx in 0..7) return idx
            return AgentSpriteIndex.forSeed(id)
        }

    /**
     * Categorized "strategy tags" summarizing how this agent bets — archetype
     * preset plus the most distinctive personality knobs, capped at 4. Always
     * returns at least the risk descriptor so the card row is never empty.
     */
    val strategyTags: List<AgentStrategyTag>
        get() {
            val tags = mutableListOf<AgentStrategyTag>()
            archetype?.let { tags += AgentStrategyTag(it.displayName, AgentStrategyKind.ARCHETYPE) }
            val p = personalityParams
            val risk = when (p.riskTolerance) {
                1 -> "Very Safe"
                2 -> "Conservative"
                3 -> "Balanced"
                4 -> "Aggressive"
                5 -> "High Risk"
                else -> null
            }
            if (risk != null) tags += AgentStrategyTag(risk, AgentStrategyKind.RISK, level = p.riskTolerance)
            when (p.preferredBetType.lowercase()) {
                "spread" -> tags += AgentStrategyTag("Spreads", AgentStrategyKind.BET_TYPE)
                "moneyline" -> tags += AgentStrategyTag("Moneylines", AgentStrategyKind.BET_TYPE)
                "total" -> tags += AgentStrategyTag("Totals", AgentStrategyKind.BET_TYPE)
            }
            val lean = when (p.underdogLean) {
                1 -> "Chalk Only"
                2 -> "Favors Favorites"
                4 -> "Likes Underdogs"
                5 -> "Underdog Hunter"
                else -> null
            }
            if (lean != null) tags += AgentStrategyTag(lean, AgentStrategyKind.LEAN)
            if (p.chaseValue) tags += AgentStrategyTag("Value Hunter", AgentStrategyKind.VALUE)
            if (p.fadePublic == true) tags += AgentStrategyTag("Fades Public", AgentStrategyKind.FADE)
            return tags.take(4)
        }
}

/** Agent combined with its cached performance row (client composite, not serialized). */
data class AgentWithPerformance(
    var agent: Agent,
    var performance: AgentPerformance? = null,
) {
    val id: String get() = agent.id

    /**
     * Build a display model from a public-leaderboard row so Search can render
     * the same card the Agents tab uses. Personality/archetype aren't in the
     * leaderboard projection, so strategy chips are absent.
     */
    constructor(entry: AgentLeaderboardEntry) : this(
        agent = Agent(
            id = entry.avatarId,
            userId = entry.userId,
            name = entry.name,
            avatarEmoji = entry.avatarEmoji,
            avatarColor = entry.avatarColor,
            preferredSports = entry.preferredSports,
            archetype = null,
            isPublic = true,
            createdAt = "",
        ),
        performance = AgentPerformance(
            avatarId = entry.avatarId,
            totalPicks = entry.totalPicks,
            wins = entry.wins,
            losses = entry.losses,
            pushes = entry.pushes,
            winRate = entry.winRate,
            netUnits = entry.netUnits,
            currentStreak = entry.currentStreak,
            bestStreak = entry.bestStreak,
        ),
    )
}

/** Category of a strategy tag, used to color-code the agent card's bottom info row. */
enum class AgentStrategyKind(val raw: String) {
    ARCHETYPE("archetype"),
    RISK("risk"),
    BET_TYPE("betType"),
    LEAN("lean"),
    VALUE("value"),
    FADE("fade"),
}

/** A single strategy descriptor + its category (client-only). */
data class AgentStrategyTag(
    val text: String,
    val kind: AgentStrategyKind,
    /** `risk_tolerance` (1…5) for risk tags so the card can color by level. */
    val level: Int = 0,
) {
    val id: String get() = "${kind.raw}-$text"
}
