import Foundation

/// Maps an agent to one of the 8 pixel-office sprite sheets (`avatar_0`…
/// `avatar_7`). The office historically assigned characters by list position
/// (`idx % 8`), so the same agent could change character on reorder and the
/// card never showed it at all. We instead derive a *stable* index from a hash
/// of the agent's id, so an agent always shows the same character everywhere —
/// the avatar tile on its card and the little guy sitting at its desk.
public enum AgentSpriteIndex {
    /// Deterministic 0…7 character index from any stable seed (FNV-1a — Swift's
    /// `String.hashValue` is per-process randomized, so we can't use it).
    /// Stable across launches and roster order.
    public static func forSeed(_ seed: String) -> Int {
        var h: UInt64 = 0xcbf2_9ce4_8422_2325
        for b in seed.utf8 { h = (h ^ UInt64(b)) &* 0x0000_0100_0000_01b3 }
        return Int(h % 8)
    }
}

/// Codable mirror of an `avatar_profiles` row in main Supabase. Field names
/// match the DB columns byte-for-byte (snake_case in JSON, camelCase in Swift
/// via `CodingKeys`).
///
/// Ports the RN `AgentProfile` interface from `types/agent.ts:106-129`. The
/// `personality_params` and `custom_insights` JSONB columns are decoded into
/// their own `AgentPersonalityParams` / `AgentCustomInsights` structs.
///
/// Designed to be `Sendable` + `Hashable` so we can use it as a NavigationStack
/// path value and in `LazyVGrid`'s `id:` parameter.
public struct Agent: Codable, Identifiable, Sendable, Hashable {
    public let id: String
    public let userId: String
    public var name: String
    public var avatarEmoji: String
    public var avatarColor: String
    public var preferredSports: [AgentSport]
    public var archetype: AgentArchetype?
    public var personalityParams: AgentPersonalityParams
    public var customInsights: AgentCustomInsights
    public var isPublic: Bool
    public var isActive: Bool
    public let createdAt: String
    public var updatedAt: String
    public var autoGenerate: Bool
    public var autoGenerateTime: String
    public var autoGenerateTimezone: String
    public var isWidgetFavorite: Bool
    public var lastGeneratedAt: String?
    public var lastAutoGeneratedAt: String?
    public var ownerLastActiveAt: String?
    public var dailyGenerationCount: Int
    public var lastGenerationDate: String?

    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case name
        case avatarEmoji = "avatar_emoji"
        case avatarColor = "avatar_color"
        case preferredSports = "preferred_sports"
        case archetype
        case personalityParams = "personality_params"
        case customInsights = "custom_insights"
        case isPublic = "is_public"
        case isActive = "is_active"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case autoGenerate = "auto_generate"
        case autoGenerateTime = "auto_generate_time"
        case autoGenerateTimezone = "auto_generate_timezone"
        case isWidgetFavorite = "is_widget_favorite"
        case lastGeneratedAt = "last_generated_at"
        case lastAutoGeneratedAt = "last_auto_generated_at"
        case ownerLastActiveAt = "owner_last_active_at"
        case dailyGenerationCount = "daily_generation_count"
        case lastGenerationDate = "last_generation_date"
    }

    public init(
        id: String,
        userId: String,
        name: String,
        avatarEmoji: String,
        avatarColor: String,
        preferredSports: [AgentSport],
        archetype: AgentArchetype?,
        personalityParams: AgentPersonalityParams = .default,
        customInsights: AgentCustomInsights = .empty,
        isPublic: Bool = false,
        isActive: Bool = true,
        createdAt: String,
        updatedAt: String,
        autoGenerate: Bool = true,
        autoGenerateTime: String = "09:00",
        autoGenerateTimezone: String = "America/New_York",
        isWidgetFavorite: Bool = false,
        lastGeneratedAt: String? = nil,
        lastAutoGeneratedAt: String? = nil,
        ownerLastActiveAt: String? = nil,
        dailyGenerationCount: Int = 0,
        lastGenerationDate: String? = nil
    ) {
        self.id = id
        self.userId = userId
        self.name = name
        self.avatarEmoji = avatarEmoji
        self.avatarColor = avatarColor
        self.preferredSports = preferredSports
        self.archetype = archetype
        self.personalityParams = personalityParams
        self.customInsights = customInsights
        self.isPublic = isPublic
        self.isActive = isActive
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.autoGenerate = autoGenerate
        self.autoGenerateTime = autoGenerateTime
        self.autoGenerateTimezone = autoGenerateTimezone
        self.isWidgetFavorite = isWidgetFavorite
        self.lastGeneratedAt = lastGeneratedAt
        self.lastAutoGeneratedAt = lastAutoGeneratedAt
        self.ownerLastActiveAt = ownerLastActiveAt
        self.dailyGenerationCount = dailyGenerationCount
        self.lastGenerationDate = lastGenerationDate
    }

    /// Tolerant decoding so list queries (which use the slim column projection
    /// in agentService.ts — no `personality_params` / `custom_insights`) still
    /// decode. Missing JSONB defaults to the canonical defaults.
    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try c.decode(String.self, forKey: .id)
        self.userId = try c.decode(String.self, forKey: .userId)
        self.name = try c.decode(String.self, forKey: .name)
        self.avatarEmoji = (try? c.decode(String.self, forKey: .avatarEmoji)) ?? "\u{1F916}"
        self.avatarColor = (try? c.decode(String.self, forKey: .avatarColor)) ?? "#6366f1"
        self.preferredSports = (try? c.decode([AgentSport].self, forKey: .preferredSports)) ?? []
        self.archetype = try? c.decodeIfPresent(AgentArchetype.self, forKey: .archetype)
        self.personalityParams = (try? c.decode(AgentPersonalityParams.self, forKey: .personalityParams)) ?? .default
        self.customInsights = (try? c.decode(AgentCustomInsights.self, forKey: .customInsights)) ?? .empty
        self.isPublic = (try? c.decode(Bool.self, forKey: .isPublic)) ?? false
        self.isActive = (try? c.decode(Bool.self, forKey: .isActive)) ?? true
        self.createdAt = try c.decode(String.self, forKey: .createdAt)
        self.updatedAt = (try? c.decode(String.self, forKey: .updatedAt)) ?? self.createdAt
        self.autoGenerate = (try? c.decode(Bool.self, forKey: .autoGenerate)) ?? true
        self.autoGenerateTime = (try? c.decode(String.self, forKey: .autoGenerateTime)) ?? "09:00"
        self.autoGenerateTimezone = (try? c.decode(String.self, forKey: .autoGenerateTimezone)) ?? "America/New_York"
        self.isWidgetFavorite = (try? c.decode(Bool.self, forKey: .isWidgetFavorite)) ?? false
        self.lastGeneratedAt = try? c.decodeIfPresent(String.self, forKey: .lastGeneratedAt)
        self.lastAutoGeneratedAt = try? c.decodeIfPresent(String.self, forKey: .lastAutoGeneratedAt)
        self.ownerLastActiveAt = try? c.decodeIfPresent(String.self, forKey: .ownerLastActiveAt)
        self.dailyGenerationCount = (try? c.decode(Int.self, forKey: .dailyGenerationCount)) ?? 0
        self.lastGenerationDate = try? c.decodeIfPresent(String.self, forKey: .lastGenerationDate)
    }
}

/// Agent combined with its cached performance row. Mirrors RN
/// `AgentWithPerformance` (`types/agent.ts:257-259`).
public struct AgentWithPerformance: Identifiable, Sendable, Hashable {
    public var agent: Agent
    public var performance: AgentPerformance?

    public var id: String { agent.id }

    public init(agent: Agent, performance: AgentPerformance? = nil) {
        self.agent = agent
        self.performance = performance
    }
}

/// Category of a strategy tag, used to color-code the AgentRowCard's bottom
/// info row (mirrors how the MLB game card colors its O/U + ML edge values).
public enum AgentStrategyKind: String, Sendable, Hashable {
    case archetype, risk, betType, lean, value, fade
}

/// A single strategy descriptor + its category, so the card can give each tag a
/// distinct colored font.
public struct AgentStrategyTag: Sendable, Hashable, Identifiable {
    public let text: String
    public let kind: AgentStrategyKind
    /// `risk_tolerance` (1...5) for risk tags so the card can color by level.
    public let level: Int
    public var id: String { "\(kind.rawValue)-\(text)" }

    public init(text: String, kind: AgentStrategyKind, level: Int = 0) {
        self.text = text
        self.kind = kind
        self.level = level
    }
}

extension Agent {
    /// Stable pixel-office character index (0…7) for this agent — see
    /// `AgentSpriteIndex`. Shown on the agent's avatar tiles and in the office.
    public var spriteIndex: Int { AgentSpriteIndex.forSeed(id) }

    /// Categorized "strategy tags" summarizing how this agent bets — its
    /// archetype preset (if any) plus the most distinctive personality knobs.
    /// Shown in the AgentRowCard's bottom strategy row. Always returns at least
    /// the risk descriptor so the row is never empty.
    public var strategyTags: [AgentStrategyTag] {
        var tags: [AgentStrategyTag] = []
        if let archetype { tags.append(.init(text: archetype.displayName, kind: .archetype)) }
        let p = personalityParams
        let riskMap = [1: "Very Safe", 2: "Conservative", 3: "Balanced", 4: "Aggressive", 5: "High Risk"]
        if let r = riskMap[p.riskTolerance] {
            tags.append(.init(text: r, kind: .risk, level: p.riskTolerance))
        }
        switch p.preferredBetType.lowercased() {
        case "spread": tags.append(.init(text: "Spreads", kind: .betType))
        case "moneyline": tags.append(.init(text: "Moneylines", kind: .betType))
        case "total": tags.append(.init(text: "Totals", kind: .betType))
        default: break
        }
        let dogMap = [1: "Chalk Only", 2: "Favors Favorites", 4: "Likes Underdogs", 5: "Underdog Hunter"]
        if let d = dogMap[p.underdogLean] { tags.append(.init(text: d, kind: .lean)) }
        if p.chaseValue { tags.append(.init(text: "Value Hunter", kind: .value)) }
        if p.fadePublic == true { tags.append(.init(text: "Fades Public", kind: .fade)) }
        return Array(tags.prefix(4))
    }
}
